Day3 ts
f-lab-edu/alg-everyday pull request #11
Opened 2024-01-05 10:51 UTC by lgyn10

2024-01-05 10:55 UTC, lgyn10 commented on day3/문자열다루기기본.ts
> +  return [4, 6].includes(s.length) && [...s].some((v: any) => isNaN(v));
기존에 `[...s].some(isNaN);`으로 지도해주셨었는데, ts-snippets이 에러를 띄워서 `(v:any)=>isNaN(v)`로 변경해보았습니다!

이전 처럼 ts-snippets을 무시하고 기존처럼 코드를 구현해야 할까요???

2024-01-05 10:55 UTC, lgyn10 commented on day3/문자열다루기기본.ts
> +  return [4, 6].includes(s.length) && [...s].some((v: any) => isNaN(v));
그리고, v요소가 number일 수도 있고 string일 수도 있어서 any로 표기했는데, 적절하게 표시한건가요??

2024-01-05 16:04 UTC, f-lab-jake requested changes

2024-01-05 16:04 UTC, f-lab-jake commented on day3/문자열다루기기본.ts
> +  return [4, 6].includes(s.length) && [...s].some((v: any) => isNaN(v));
타입에러를 다시 읽고 거기에 맞춰서 고칩시다.
타입체커를 충신으로 여겨야지 그냥 무시하면 안됩니다.

2024-01-06 07:22 UTC, lgyn10 commented on day3/문자열다루기기본.ts
> +const lo = require("lodash");
최상단 루트에 declare.ts 안에 const _ = require('lodash);로 선언한 _를 가져오지 못하는 에러가 계속 발생했습니다. 구글링해봐도 원인을 몰라 일단 lo변수로 선언해서 lodash를 사용했습니다.

혹시 이와 같은 에러를 겪어보셨나요..? 해결법을 알고 계실까요..?

2024-01-06 07:22 UTC, lgyn10 commented on day3/문자열다루기기본.ts
> +    [...s].every((v: string) => lo.isInteger(parseInt(v, 10)))
타입 체커를 확인하면서 수정해보았습니다!

2024-01-06 07:34 UTC, lgyn10 commented on day3/문자열다루기기본.ts
> +    [...s].every((v: string) => _.isInteger(parseInt(v, 10)))
타입 체커를 확인하며 수정해보았습니다! isNaN함수를 쓰는 것보다 코드 의미를 더 명시적으로 읽을 수 있게 되었습니다

2024-01-06 10:08 UTC, f-lab-jake commented on day3/문자열다루기기본.ts
> +    [...s].every((v: string) => _.isInteger(parseInt(v, 10)))
잘했습니다. `v`에 굳이 타입 명시안해도 됩니다. 그냥 추론되게 하는게 더 안전합니다.

2024-01-06 10:22 UTC, lgyn10 commented on day3/문자열다루기기본.ts
> +    [...s].every((v: string) => _.isInteger(parseInt(v, 10)))
오 타입 지정이 필수가 아니였군요.. 역시 아직 타입스크립트 사용이 미숙하네요

2024-01-06 13:06 UTC, f-lab-jake approved these changes

2024-01-06 13:32 UTC, merged