day5 ts 변환
f-lab-edu/alg-everyday pull request #13
Opened 2024-01-05 14:03 UTC by lgyn10

ts로 변환 및 리펙토링을 진행하였습니다~!

2024-01-05 14:14 UTC, lgyn10 commented on day5/삼총사.ts
> +          v1 + v2 + v3 === 0 && arr.push([v1, v2, v3].sort((a, b) => a - b)),
먼저 저번에 지도해주셨는데, 같은 실수를 했네요..
map의 리턴값을 쓰지 않아 forEach로 수정하였고, 저도 까먹었는데 map안에 unshift함수가 있던 것을 지양하라는 말씀을 하셨었네용 다음 멘토링 시간에 이와 관련해서 저도 잊지 않고 질문드리겠습니다~!

2024-01-05 14:14 UTC, lgyn10 commented on day5/최소직사각형.ts
> +  return _.max(getSmallValOfSize) * _.max(getLagreValOfSize);
변수에 코드의 의미를 두어 표현해봤는데, 이런식으로 쓰는 건가요..?

2024-01-05 14:14 UTC, lgyn10 commented on day5/시저암호.ts
> +  const azNum = 26;
먼저 magic number들을 상수 선언을 통해 의미를 부여했습니다!

2024-01-05 14:14 UTC, lgyn10 commented on day5/시저암호.ts
> +}
기존에 `ascNumSum > x ? ascNumSum - y : ascNumSum`는 대문자 또는 소문자 26개의 알파벳을 순환하도록 동작합니다. 
하지만, 직관적으로 어떤 동작을 의미하는지 알기 힘들어서 1번 함수와 같이 기준점 알파벳으로부터 얼마나 떨어진 알파벳인지 동작하도록 표현해보았습니다~!

2024-01-05 14:14 UTC, lgyn10 commented on day5/시저암호.ts
> +      return basisNum + ((ascNumSum - basisNum) % azNum);
2번 함수는 중복되는 리턴문을 피하기 위해 if-elseif-else로 이어지는 조건문으로 표현해보았습니다. 
2번 함수를 통해 중복을 피하면서 더 가독성 좋은 코드를 작성하고 싶었지만, 저한테는 좀 지저분해보여 1번 코드가 가독성이 좋아보입니다.
흠.. 사실 2개 함수 모두 아직 읽기 부담스러운 코드인 것 같아요....🫠

2024-01-05 16:09 UTC, f-lab-jake requested changes

2024-01-05 16:09 UTC, f-lab-jake commented on day5/삼총사.ts
> +          v1 + v2 + v3 === 0 && arr.push([v1, v2, v3].sort((a, b) => a - b)),
변경을 `&&` 로 제어하는 것도 피합시다. 비슷한 이유입니다.

2024-01-05 16:09 UTC, f-lab-jake commented on day5/시저암호.ts
> +      let basisNum: number;
let 사용을 피해봅시다.

2024-01-05 16:09 UTC, f-lab-jake commented on day5/시저암호.ts
> +      else return space_ASCII;
중간에 return 처럼 플로우를 바꾸는 로직은 가능하면 코드 앞부분으로 보냅시다.

2024-01-05 16:09 UTC, f-lab-jake commented on day5/최소직사각형.ts
> +  return _.max(getSmallValOfSize) * _.max(getLagreValOfSize);
`getSmallValOfSize` 요건 함수명이 맞겠죠?
그리고 배열이면 뒤에 s붙여서 복수형으로 만듭시다.
`shortSides`, `longSides` 정도가 좋겠네요.

2024-01-06 08:58 UTC, lgyn10 commented on day5/삼총사.ts
> +          v1 + v2 + v3 === 0 && arr.push([v1, v2, v3].sort((a, b) => a - b)),
흠.. 그럼 
```
  num.forEach((v3) => {
        if (v1 + v2 + v3 === 0)
          return arr.push([v1, v2, v3].sort((a, b) => a - b));
      }),
```
이런식으로 if문을 이용해야할까요? 하지만, 이런 코드를 &&로 줄여보라고 하셨었는데, 그떄와 지금의 차이를 잘 모르겠습니다. 아직 map함수 안에서 외부 변수에 변경을 주지 않는 이유를 모르니, 코드 수정의 방향성을 잡지 못하겠군요... 
어떤 측면의 이유로 코드 수정이 필요하다고 생각하시나요?? 어떤 개념을 찾아 보면 좋을까요?

2024-01-06 08:58 UTC, lgyn10 commented on day5/시저암호.ts
> +      let basisNum: number;
let 사용을 피하면 아래의 `return basisNum + ((ascNumSum - basisNum) % azNum);`식을 쓸 수가 없군요. 그럼 결국 함수 1과 같이 짜는 것이 정답이라는 말씀이실까요??

2024-01-06 08:58 UTC, lgyn10 commented on day5/시저암호.ts
> +      else return space_ASCII;
이 부분도 결국 수정해보면 코드가 함수 1과 다를 바 없는 로직인 것 같습니다

2024-01-06 09:01 UTC, lgyn10 commented on day5/시저암호.ts
> +    })
`return space_ASCII;`앞으로 가져오니 더 이상해지는 건....왜...이...러...죠..?ㅠㅠㅠㅠㅠ 결국 또 `else return space_ASCII`로 중복되니 함수 1번이 역시 정답이지 않나 하는 생각입니다.. 

함수 1과 함수 2 중에 멘토님은 어떤 코드가 더 가독성 좋은 코드라고 보시나요?

2024-01-06 10:08 UTC, f-lab-jake requested changes

2024-01-06 10:08 UTC, f-lab-jake commented on day5/삼총사.ts
> +          return arr.push([v1, v2, v3].sort((a, b) => a - b));
return을 한 값을 쓰나요?

2024-01-06 10:08 UTC, f-lab-jake commented on day5/시저암호.ts
> +      let basisNum: number;
아뇨 순서를 바꿔서 해결할 수 있습니다.

2024-01-06 10:28 UTC, lgyn10 commented on day5/삼총사.ts
> +          return arr.push([v1, v2, v3].sort((a, b) => a - b));
아~~~!~!~!~!!!!! 거기에서 차이가 있던 거군요...!!!!!!!!😲

2024-01-06 11:33 UTC, lgyn10 commented on day5/시저암호.ts
> +}
순서를 바꾸라고 말씀하시는 것이, 선언하는 시점을 바꿔보라는 말로 해석됩니다. 그래서 위와 같이 수정해보았는데, 여전히 답은 아닌것 같군요.... 순서를 바꾸라는 말씀을 이해하지 못하겠습니다.

2024-01-06 13:08 UTC, f-lab-jake requested changes

2024-01-06 13:08 UTC, f-lab-jake commented on day5/시저암호.ts
> +}
거의 다왔습니다. 다만 `basisNum === space_ASCII ? space_ASC` 요게 별로 안좋은 분기입니다. 그냥 공백이면 일찌감치 공백을 리턴해버리세요.

2024-01-08 07:11 UTC, lgyn10 commented on day5/시저암호.ts
> +          : space_ASCII;
앞에서 공백일 때 `space_ASCII`를 리턴하게끔 했는데, 이 부분에서 다시 `space_ASCII를 리턴하도록 짜는게 맞는건가요..? 
`isLower(v) && a_ASCII`로 간략화하려니 ts 체커가 `basisNum`이 null 값을 가질 수 있다고 해서 에러가 뜨는데, 사실 인자로 들어오는 s값이 제대로만 들어온다면 null 값은 나올리가 없는데 말이죠.. 흠..

2024-01-08 08:02 UTC, f-lab-jake requested changes

2024-01-08 08:02 UTC, f-lab-jake commented on day5/시저암호.ts
> +          : space_ASCII;
아 그 처리는 멘토링때 알려드리죠. 일단은 `isUpper` 아니면 lower라고 간주합시다. 입력이 약속을 지키면 옳은 코드입니다.

2024-01-08 12:15 UTC, lgyn10 commented on day5/시저암호.ts
> +}
공백이냐 아니냐를 먼저 처리할 수 있다면 `isLower`함수를 삭제하고 `isUpper`함수만 사용해서 대문자 소문자를 구분할 수 있게 되어 다음과 같이 코드를 줄이게 되었습니다! 굳이 `isUpper`와 `isLower`함수를 둘 다 사용하려고 하니 이전 같은 실수가 나온 듯 합니다

2024-01-08 14:32 UTC, f-lab-jake requested changes

2024-01-08 14:32 UTC, f-lab-jake commented on day5/시저암호.ts
>    const azNum = 26;
잘했습니다. 이제 여기에 `charCodeAt`를 써서 magic number만 제거하면 끝입니다.

2024-01-08 15:11 UTC, lgyn10 commented on day5/시저암호.ts
>    const azNum = 26;
아! 저 숫자 자체를 안 쓰는 거군요!

2024-01-08 15:11 UTC, lgyn10 commented on day5/시저암호.ts
> +  const azNum = "Z".charCodeAt(0) - A_ASCII + 1;
magic number 제거 완료했습니다!!!!

2024-01-11 05:07 UTC, f-lab-jake approved these changes

2024-01-11 07:39 UTC, merged