day6
f-lab-edu/alg-everyday pull request #14
Opened 2024-01-06 13:03 UTC by lgyn10

2024-01-06 13:04 UTC, lgyn10 commented on day6/문자열내마음대로정렬하기.ts
> +  return _.sortBy(s, (v: string) => v.slice(n));
lodash 함수가 엄청나군요

2024-01-06 13:12 UTC, f-lab-jake requested changes

2024-01-06 13:12 UTC, f-lab-jake commented on day6/가장가까운같은글자.ts
> +  );
잘 이해가 안됩니다. 무슨 문제인지 짐작도 잘 안가는 상황인데요.
일단 문제 링크를 맨 앞에 주석으로 달아주세요.
그리고 중간 변수들에 이름을 붙일수있으면 그렇게 합시다.

2024-01-06 13:12 UTC, f-lab-jake commented on day6/숫자문자열과영단어.ts
> +  numArr.forEach((v) => (s = _.replace(s, v, map.get(v))));
`(s = ...)` 대신 `{ s = ... }` 로 합시다. 다른 문제도 다요.
이유는 나중에 설명하죠.

2024-01-08 07:12 UTC, lgyn10 commented on day6/가장가까운같은글자.ts
> +// https://school.programmers.co.kr/learn/courses/30/lessons/142086
문제 링크 앞으로 이렇게 넣어놓겠습니당!

2024-01-08 07:12 UTC, lgyn10 commented on day6/가장가까운같은글자.ts
> +};
좀 직관적인 의미를 나타내도록 수정해보았습니다~!

2024-01-08 08:04 UTC, f-lab-jake requested changes

2024-01-08 08:04 UTC, f-lab-jake commented on day6/가장가까운같은글자.ts
> +  const findLastIndex = (str: string, char: string) => str.lastIndexOf(char);
요런 함수는 안만들어도됩니다.

2024-01-08 08:04 UTC, f-lab-jake commented on day6/가장가까운같은글자.ts
> +        : idx - findLastIndex(s.slice(0, idx), val), // 자신보다 앞에 같은 글자가 있을 때
여기서 중간 변수에 이름을 주세요.
문제를 못봐서 이해하기어려웠던 부분도 있네요.

2024-01-08 12:15 UTC, lgyn10 commented on day6/가장가까운같은글자.ts
> +  const findLastIndex = (str: string, char: string) => str.lastIndexOf(char);
넵..!

2024-01-08 14:30 UTC, f-lab-jake approved these changes
O(N)으로도 한번 풀어보세요.

2024-01-08 15:13 UTC, lgyn10 commented
> O(N)으로도 한번 풀어보세요.

넵!

2024-01-09 08:07 UTC, lgyn10 commented
> O(N)으로도 한번 풀어보세요.

힌트가 필요합니다...... 아무리 생각해도 방법이 떠오르지 않습니다. indexOf()나 lastIndexOf()함수가 이진 탐색으로 작동하도록 구현한다고 해도 O(n log n) 시간이 걸리는데, O(n)시간은 곧 map함수와 index 탐색 함수를 분리하는 방법 뿐인데, 방법이 떠오르지 않습니다....ㅠ

2024-01-11 05:13 UTC, f-lab-jake commented
지금이 O(N^2)잖아요? O(N * N) 중에서 한붑분을 1로 만들면 되겠죠?

2024-01-11 10:48 UTC, lgyn10 commented on day6/가장가까운같은글자.ts
> +};
Map 구조를 통해 O(n) 시간을 구현했습니다

2024-01-11 10:52 UTC, lgyn10 commented
> 지금이 O(N^2)잖아요? O(N * N) 중에서 한붑분을 1로 만들면 되겠죠?

풀엇습니다!

2024-01-11 10:52 UTC, merged