day7
f-lab-edu/alg-everyday pull request #15
Opened 2024-01-08 12:08 UTC by lgyn10

비밀 지도
https://school.programmers.co.kr/learn/courses/30/lessons/17681

푸드 파이트 대회
 https://school.programmers.co.kr/learn/courses/30/lessons/134240

k번째 수
https://school.programmers.co.kr/learn/courses/30/lessons/42748

2024-01-08 14:28 UTC, f-lab-jake requested changes

2024-01-08 14:28 UTC, f-lab-jake commented on day7/k번째수.ts
> +    const kIdx = cmd[2] - 1;
destructuring 씁시다

2024-01-08 14:28 UTC, f-lab-jake commented on day7/비밀지도.ts
> +    arr.map((v) => "0".repeat(n - v.toString(2).length) + v.toString(2));
`binaryArr`를 만들 생각을 한걸 아주 잘했습니다.

그런데 더 다루기 쉬운 형태로 만들어 놓는게 좋습니다. 밑에보면 다시 `parseInt` 하잖아요?
이 단계에서 문제푸는데 필요한 형태로 미리 준비합시다.

값의 의미가 아닌 값의 형태만 바꾸는 코드들은 한군데 몰아놓고 나머지 부분에서는 형태에 신경안쓰게 해주는게 좋습니다.

2024-01-08 14:28 UTC, f-lab-jake commented on day7/푸드파이트대회.ts
> +  for (const foodIdx in usableFoodForHalf) {
`usableFoodForHalf.keys()` 씁시다.

2024-01-08 14:28 UTC, f-lab-jake commented on day7/푸드파이트대회.ts
> +    foodCnt && foodArr.push(foodIdx.repeat(foodCnt));
변경할때 `&&` 사용 피합시다
`&&`도 리턴값을 활용할때만 쓰세요.

2024-01-08 14:28 UTC, f-lab-jake commented on day7/푸드파이트대회.ts
> +  return foodArr.join("") + "0" + foodArr.reverse().join("");
`join`을 한번만 써보세요.

2024-01-09 07:30 UTC, lgyn10 commented on day7/k번째수.ts
> +    const [firstNumIdx, lastNumIdx, kIdx] = cmd.map((v) => v - 1);
구조분해할당이 이렇게 편리하군요

2024-01-09 07:30 UTC, lgyn10 commented on day7/비밀지도.ts
> +};
값의 의미가 중요한 연산 로직 부분과 값의 형태만 건드리는 코드를 분리해보았습니다. 이전 코드가 더 가독성이 좋을까요?

2024-01-09 07:30 UTC, lgyn10 commented on day7/푸드파이트대회.ts
> +  return [...foodArr, 0, ...foodArr.reverse()].join("");
제가 생각이 짧았었군요..

2024-01-09 07:31 UTC, lgyn10 commented on day7/푸드파이트대회.ts
> +  for (const idx of usableFoodForHalf.keys()) {
이런식으로 `.keys()`사용을 유도하신거 맞을까요...?

2024-01-09 07:31 UTC, lgyn10 commented on day7/푸드파이트대회.ts
> +      foodArr.push(String(idx).repeat(usableFoodForHalf[idx]));
리턴값을 사용하지 않는 &&을 피하고, 단순 if문으로 수정했습니다.

2024-01-11 05:11 UTC, f-lab-jake requested changes

2024-01-11 05:11 UTC, f-lab-jake commented on day7/비밀지도.ts
> +};
`zipWith`하기 전에 `arr1`과 `arr2`에 전처리를 끝내놓읍시다.

그리고  `map` 두번은 합쳐줄수 있습니다.

2024-01-11 10:45 UTC, lgyn10 commented on day7/비밀지도.ts
> +};
지금 보니, `arr1`과 `arr2`의 전치리 과정이 필요가 없었네요

2024-01-11 10:54 UTC, lgyn10 commented on day7/비밀지도.ts
> +};
지금보니 `arr1`과 `arr2`는 전처리가 필요 없었네요.. map도 하나도 합쳤습니다!

2024-01-11 11:23 UTC, f-lab-jake approved these changes

2024-01-11 12:00 UTC, merged