day8
f-lab-edu/alg-everyday pull request #16
Opened 2024-01-10 13:19 UTC by lgyn10

2024-01-11 02:41 UTC, f-lab-jake requested changes

2024-01-11 02:41 UTC, f-lab-jake commented on day8/두개뽑아서더하기.ts
> +  }
`flatMap` 써보세요

2024-01-11 11:59 UTC, lgyn10 commented on day8/두개뽑아서더하기.ts
> +  }
flatMap함수로 for문을 대체하는 건가요??
중첩배열을 평탄화하는데 사용된다고 해서 사용해봤는데, 원하시는 코드가 아닐 것 같다는 생각이 듭니다..?!ㅠ 일부러 중첩 배열을 만들어야 하나요...?

2024-01-11 11:59 UTC, lgyn10 commented on day8/두개뽑아서더하기.ts
> +};
`flatMap`을 사용한 코드입니다

2024-01-13 15:03 UTC, f-lab-jake requested changes

2024-01-13 15:03 UTC, f-lab-jake commented on day8/두개뽑아서더하기.ts
> +};
`push`를 안쓸수있습니다

2024-01-13 15:23 UTC, lgyn10 commented
# 피드백 사항
### 두개 뽑아서 더하기
- `flatMap`을 통해 `arr` 변경을 피하기
- `push()` 사용하지 않기

2024-01-15 10:27 UTC, f-lab-jake requested changes

2024-01-15 10:27 UTC, f-lab-jake commented on day8/두개뽑아서더하기.ts
> +    numbers.filter((_, i) => i !== idx).map((v) => numbers[idx] + v),
x + y = y + x 잖아요? 두번 반복하지 맙시다.

2024-01-15 14:18 UTC, lgyn10 commented on day8/두개뽑아서더하기.ts
> +    numbers.filter((_, i) => i < idx).map((v) => numbers[idx] + v),
중복 처리했습니다!

2024-01-15 14:19 UTC, lgyn10 commented
> # 피드백 사항
> ### 두개 뽑아서 더하기
> * `flatMap`을 통해 `arr` 변경을 피하기
> * `push()` 사용하지 않기
- x+y = y+x 중복 제거 (filter 제대로 쓰기)

2024-01-16 08:02 UTC, lgyn10 commented on day8/두개뽑아서더하기.ts
> +    numbers.filter((_, i) => i < idx).map((v) => numbers[idx] + v),
@f-lab-jake 
피드백 부탁드립니다! 🫡

2024-01-16 08:53 UTC, f-lab-jake requested changes

2024-01-16 08:53 UTC, f-lab-jake commented on day8/두개뽑아서더하기.ts
> +    numbers.filter((_, i) => i < idx).map((v) => numbers[idx] + v),
`numbers.filter((_, i) => i < idx)`의 진짜 의미가 뭔가요? 뭘 하려는 코드죠?

2024-01-17 05:27 UTC, lgyn10 commented on day8/두개뽑아서더하기.ts
> +    numbers.filter((_, i) => i < idx).map((v) => numbers[idx] + v),
@f-lab-jake 
[2, 1, 3, 4, 1] 중에서 2을 뽑아서 나머지 [1,3,4,1]에 더하고
그 다음 1을 뽑으면 첫 번째 2을 제외한 [3,4,1]에 더하고
3을 뽑으면 [4,1]에 더하고
4를 뽑으면 [1]에 더하는 로직을 구현하려고 했습니다. 

다시 보니, `numbers.filter((_, i) => i < idx)` 에서 `i < idx`가 아니라 `idx < i`여야 위와 같은 의미로 사용될 것 같습니다

flatmap, filter, map을 한 줄로 쓰려다보니 의미를 파악하기가 쉽지 않네요...
이런 식은 의미 파악이 어려워지면 끊어서 구현하는 것이 의미 파악에는 도움이 될 것 같다는 생각이 듭니다!

2024-01-17 07:54 UTC, f-lab-jake commented on day8/두개뽑아서더하기.ts
> +    numbers.filter((_, i) => i < idx).map((v) => numbers[idx] + v),
`slice`를 쓰란 얘기였습니다.

2024-01-18 11:36 UTC, f-lab-jake requested changes

2024-01-18 11:36 UTC, f-lab-jake commented on day8/두개뽑아서더하기.ts
> +  return uniq(sums).sort((a: number, b: number) => a - b);
`: number` 요런 타이핑 빼는게 낫습니다.

2024-01-18 18:18 UTC, lgyn10 commented on day8/두개뽑아서더하기.ts
> +  return uniq(sums).sort((a: number, b: number) => a - b);
넵!

2024-01-19 02:28 UTC, f-lab-jake approved these changes

2024-01-19 02:48 UTC, f-lab-jake approved these changes

2024-01-19 08:24 UTC, merged