day9
f-lab-edu/alg-everyday pull request #17
Opened 2024-01-11 16:01 UTC by lgyn10

2024-01-13 15:05 UTC, f-lab-jake requested changes

2024-01-13 15:05 UTC, f-lab-jake commented on day9/날짜2016년.ts
> +};
`Date`쓰지않고 해볼까요?

2024-01-13 15:05 UTC, f-lab-jake commented on day9/명예의전당1.ts
> +    return ranking.length > k ? ranking[k - 1] : ranking[ranking.length - 1];
`ranking[...]`의 형태가 보이죠?

2024-01-13 15:05 UTC, f-lab-jake commented on day9/추억점수.ts
> +    _.sum(album.map((name) => (scoreMap.has(name) ? scoreMap.get(name) : 0))),
`has`와 `get`을 동시에 쓰지맙시다. 왤까요?

2024-01-13 15:27 UTC, lgyn10 commented
# 피드백 사항
### 명예의전당1
- 비슷한 로직을 최대한 ()로 묶기
### 추억함수
- Map에서 `has()`와 `get()`을 동시에 쓰지 않는 이유

2024-01-15 06:49 UTC, lgyn10 commented on day9/명예의전당1.ts
> +    return ranking.length > k ? ranking[k - 1] : ranking[ranking.length - 1];
이런 류의 식이 익숙해지기가 쉽지 않군요. 말씀해주시니 너무나도 잘 보이네요🧐

2024-01-15 06:53 UTC, lgyn10 commented on day9/날짜2016년.ts
> +};
베열을 통해 만들었는데, 일 수와 요일은 정해져 있기에 배열에서 오는 메모리 낭비는 없을 것 같습니다..!

2024-01-15 10:37 UTC, lgyn10 commented on day9/추억점수.ts
> +    _.sum(album.map((name) => (scoreMap.has(name) ? scoreMap.get(name) : 0))),
@f-lab-jake 
제가 개념을 제대로 잡고 있는지 확인하고 싶은데, 혹시 설명이 맞다면 따봉 부탁드려요...!

2024-01-15 10:45 UTC, f-lab-jake commented on day9/추억점수.ts
> +    _.sum(album.map((name) => (scoreMap.has(name) ? scoreMap.get(name) : 0))),
`get() ?? 0` 가 맞습니다.

2024-01-15 13:16 UTC, merged