day10
f-lab-edu/alg-everyday pull request #18
Opened 2024-01-12 14:22 UTC by lgyn10

이번 문제 중 `기사단원의무기`와 `덧칠하기`에서는 let을 쓰는 것이 가독성이 좋다고 생각해서 사용했습니다. 
const를 사용하면 배열 구조로 밖에 떠오르지 않고, 배열 구조를 쓰자니 너무 불필요한 가공이 많이 일어납니다.

이 두 문제의 경우에서는 let을 써도 무방할까요??

2024-01-13 03:13 UTC, f-lab-jake requested changes

2024-01-13 03:13 UTC, f-lab-jake commented on day10/기사단원의무기.ts
> +    .fill(0)
`range`씁시다

2024-01-13 03:13 UTC, f-lab-jake commented on day10/기사단원의무기.ts
> +          if (j === Math.sqrt(number)) cnt--;
안좋은 분기문입니다.

2024-01-13 03:13 UTC, f-lab-jake commented on day10/기사단원의무기.ts
> +      return cnt > limit ? power : cnt; //
`min` 씁시다.

2024-01-13 03:13 UTC, f-lab-jake commented on day10/덧칠하기.ts
> +  }
`wall.length`가 커지면 비효율적인 구현이 됩니다. 다른 풀이를 찾아봅시다.

2024-01-13 03:13 UTC, f-lab-jake commented on day10/모의고사.ts
> +  });
`map`을 쓸수있습니다.

2024-01-13 03:13 UTC, f-lab-jake commented on day10/소수찾기.ts
> +  const totalArr = Array(n + 1).fill(true);
n이커지면 메모리를 많이먹겠죠? 이걸 안쓰는 답을 찾읍시다.

2024-01-13 08:06 UTC, lgyn10 commented on day10/소수찾기.ts
> +  const totalArr = Array(n + 1).fill(true);
```
const solution = (n) => {
  let cnt=0;
  for (let i = 2; i <= n; i++) {
    let isPrime = true;
    for (let j = 2; j <= Math.sqrt(i); j++) {
      if (i % j === 0) isPrime = false;
    }
    if (isPrime === true) cnt++;
  }
  return cnt;
}
```
이 풀이가 에라토스테네스의 체를 적용하지 않고 푼 풀이인데요. 여기에서는 n이 커지는 만큼 해당 배열을 만들지 않아서 메모리 상의 이득을 챙길 수는 있으나, 시간초과로 통과하지 못하더라구요...!

2024-01-13 09:51 UTC, lgyn10 commented
# 피드백 사항
### 덧칠하기
- 메모리 효율 개선
###기사단원의 무기
- `_.range()` 활용
- `_.min()` 활용
- 안 좋은 분기점 처리
### 모의 고사
- `map`사용
### 소수 찾기
- 메모리 효율 개선

2024-01-13 10:14 UTC, lgyn10 commented on day10/기사단원의무기.ts
> +    .fill(0)
기능적으로 같은 결과인데, `range` 메서드를 권장하시는 이유가 궁금해요?!

2024-01-13 10:34 UTC, lgyn10 commented on day10/기사단원의무기.ts
> +      return cnt > limit ? power : cnt; //
`return _.min([cnt, limit]) === cnt ? power : cnt;`
이와 같이 표현하면 무엇을 표현하는지 더 명확히 보여서 min()을 쓰라고 권장하시는 걸까요? 
맞다면, 이상하게 number 형식에는 min 타입이 없다는 에러가 계속 떠서 사용을 못하고 있어요🥹

2024-01-13 11:05 UTC, f-lab-jake commented on day10/소수찾기.ts
> +  const totalArr = Array(n + 1).fill(true);
이 방법에서 더 개선할수있습니다.

2024-01-15 15:07 UTC, lgyn10 commented
> # 피드백 사항
> ### 덧칠하기
> * 메모리 효율 개선
> 
> ### 기사단원의 무기
> * `_.range()` 활용
> * `_.min()` 활용 -> Math.min()을 활용하자
> * 안 좋은 분기점 처리
> 
> ### 모의 고사
> * `map`사용
> 
> ### 소수 찾기
> * 메모리 효율 개선

2024-01-15 15:15 UTC, lgyn10 commented on day10/기사단원의무기.ts
> +      return Math.min(cnt, limit) === cnt ? power : cnt;
`_.min` 사용이 어려워 `Math.min()`을 사용했습니다!

2024-01-15 15:15 UTC, lgyn10 commented on day10/소수찾기.ts
> +};
아무리 생각해도 개선 방안이 생각안나고 답답해서 답안을 찾아봤습니다..ㅠ

2024-01-16 02:05 UTC, f-lab-jake requested changes

2024-01-16 02:05 UTC, f-lab-jake commented on day10/기사단원의무기.ts
> +    if (Math.floor(sqrtNumber) === sqrtNumber) cnt -= 1;
더해놓고 빼지 말아봅시다.

2024-01-16 02:05 UTC, f-lab-jake commented on day10/소수찾기.ts
> +  const arr: boolean[] = [];
여전히 크기 n짜리 배열이 생깁니다. 그리고 의미있는 이름을 주세요.

2024-01-16 07:41 UTC, lgyn10 commented on day10/기사단원의무기.ts
> +    if (Math.floor(sqrtNumber) === sqrtNumber) cnt -= 1;
@f-lab-jake 
이해가 어려워요. 빼지 않으면 해당 숫자의 약수의 개수를 제대로 산출할 수 없습니다. 

`제곱근 값`을 쓰지 않고 1부터 `number`까지 온전히 순환하는 것을 말씀하시는 걸까요??

2024-01-16 08:00 UTC, lgyn10 commented on day10/소수찾기.ts
> +  const arr: boolean[] = [];
@f-lab-jake 
변수명 짓는 것 신경쓰겠습니다!
그리고, 이 문제는 이제 제 스스로는 더 이상... 개선을 ,,,하지,, 못,, 하겠습니다...🫠

2024-01-16 08:54 UTC, f-lab-jake commented on day10/소수찾기.ts
> +  const arr: boolean[] = [];
`primes : number[]`라고 해서 그전까지 발견된 소수들을 저장해봅시다.

2024-01-18 06:58 UTC, lgyn10 commented
> > # 피드백 사항
> > ### 덧칠하기
> > 
> > * 메모리 효율 개선
> > 
> > ### 기사단원의 무기 🫠
> > 
> > * `_.range()` 활용
> > * `_.min()` 활용 -> Math.min()을 활용하자
> > * 안 좋은 분기점 처리
> > 
> > ### 모의 고사
> > 
> > * `map`사용
> > 
> > ### 소수 찾기
> > 
> > * 메모리 효율 개선 🫠

2024-01-20 10:08 UTC, lgyn10 commented
# 피드백 사항
### 덧칠하기
- 메모리 효율 개선
### 기사단원의 무기
- `_.range()` 활용
- `_.min()` 활용 
- 안 좋은 분기점 처리 (코드 간결화)
### 모의 고사
- `map`사용
### 소수 찾기
- 메모리 효율 개선 -> 🫠

`피드백 수정 사항 보류 (1/18)`

2024-01-20 10:12 UTC, lgyn10 commented on day10/기사단원의무기.ts
> +      }
@f-lab-jake 
안 좋은 분기점으로 지적 받은 사항들을 개선했습니다!😎

2024-01-20 15:38 UTC, lgyn10 commented on day10/소수찾기.ts
> +// https://school.programmers.co.kr/learn/courses/30/lessons/12921
오늘 소수찾기 문제도 살펴보았습니다!
피드백 주신 내용을 바탕으로 코드 수정을 해나가고, 검색하고 찾아보았지만 마땅한 방법을 찾지 못했습니다.

소수찾기1 함수는 프로그래머스 채점에서 `시간 초과`로 통과하지 못했습니다. 

소수찾기2 함수는 "에라토스테네스의 체"를 적용하여 시간 효율성을 개선하였지만, `공간 효율성`을 개선하지 못했습니다.

소수찾기3 함수는 소수찾기2 함수와 같이 "에라토스테네스의 체"를 적용하면서 `공간 효율성`을 개선한 코드였습니다. 하지만, 여전히 크기 n짜리 배열이 생성되기 때문에 공간 효율성이 좋지 않다고 피드백 주셨습니다. 

소수찾기4 함수는 `primes: number[]`를 만들어서 활용해보라고 피드백 주셨는데, 마땅한 방법이 떠오르지 않습니다. 



소수찾기 문제에 대해 많은 시간을 들이고, 고민을 충분히 한 것 같습니다.
멘토님의 답안을 받아보고 분석하는 것이 혼자서 더 고민하고 시간을 쓰는 것보다 더 가치있겠다고 판단됩니다..!

멘토님께서 생각하시는 답안을 공유해주실 수 있으실까요...??

2024-01-21 12:09 UTC, f-lab-jake requested changes

2024-01-21 12:09 UTC, f-lab-jake commented on day10/기사단원의무기.ts
> +        if (attackPoint % j === 0) cnt += j === APSqrt ? 1 : 2;
비효율적입니다. 왜그럴까요?

2024-01-21 16:48 UTC, lgyn10 commented on day10/기사단원의무기.ts
> +        if (attackPoint % j === 0) cnt += j === APSqrt ? 1 : 2;
흠.. if문에 삼항연산자를 쓰는 것을 말씀하시는 걸까요? 
어떤 측면에서 비효율적인지 잘 모르겠습니다.

2024-01-22 08:24 UTC, f-lab-jake commented on day10/기사단원의무기.ts
> +        if (attackPoint % j === 0) cnt += j === APSqrt ? 1 : 2;
`j === APSqrt`는 딱 한번 `true`죠? 매번 확인하는걸 피해보세요.

2024-01-23 07:04 UTC, lgyn10 commented on day10/기사단원의무기.ts
> +        if (attackPoint % j === 0) cnt += j === APSqrt ? 1 : 2;
```
let cnt = 0;
for (let j = 0; j <= APSqrt; j++) {
	if (number % j === 0) cnt += 2;
}
if (Math.floor(APSqrt) === APSqrt) cnt -= 1;
```
처음 이 코드에서 for문의 범위만 제대로 설정해줘도 더하기만 하는 로직으로 개선이 되는 문제였군요..

for문의 범위 설정에 대해서 크게 생각해보지 않았는데, 이번에 제대로 그 필요성을 느끼게 되네요ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ

최종 수정된 코드 커밋했습니다!

2024-01-23 08:40 UTC, f-lab-jake approved these changes

2024-01-23 08:40 UTC, f-lab-jake commented on day10/기사단원의무기.ts
> +      if (Math.floor(APSqrt) === APSqrt) cnt += 1;
또는 `j * j === attackPoint`로 해도됩니다

2024-01-23 14:31 UTC, lgyn10 commented on day10/기사단원의무기.ts
> +      if (Math.floor(APSqrt) === APSqrt) cnt += 1;
37번 줄은 for문을 벗어났기 때문에 `j` 변수를 사용할 수 없지 않나요? 

for문 안에서 `j * j === attackPoint` 를 사용하려면 
```
      for (let j = 0; j <= APSqrt; j++) {
        if (attackPoint % j === 0) {
          if (j * j === attackPoint) {
            cnt += 1;
          } else cnt += 2;
        }
      }
```
다음과 같은 코드가 될 것 같습니다....!? 근데 이러면 비효율아닌가욥...

2024-01-24 03:25 UTC, lgyn10 commented on day10/소수찾기.ts
> +// https://school.programmers.co.kr/learn/courses/30/lessons/12921
@f-lab-jake 
이것두 한번 봐주세요!

2024-01-25 04:17 UTC, f-lab-jake commented on day10/기사단원의무기.ts
> +      if (Math.floor(APSqrt) === APSqrt) cnt += 1;
`j`를 밖으로 빼면됩니다

2024-01-25 16:20 UTC, f-lab-jake requested changes

2024-01-25 16:20 UTC, f-lab-jake commented on day10/소수찾기.ts
>      }
더 개선할수 있습니다.

2024-01-26 06:51 UTC, lgyn10 commented on day10/소수찾기.ts
> +  }
1차적으로 some 메서드로 primes의 모든 요소를 순회하는 것을 방지하여 시간 효율성을 개선했습니다.
some 메서드는 true 조건이 만족되는 즉시 true를 반환하면서 순회를 종료합니다. 

그런데 문제는 
```
for (let target = 2; target <= n; target++) {
```
여기에서 2부터 n까지 모두 순회하는 것 때문에 시간 효율성 개선이 어렵더군요... 

먼저, 1차적으로 멘토님께서 기대하신 개선이 some 메소드를 통한 개선이 맞을까요?? 

그리고, 2부터 n까지 순회하는 것을 이제 개선해야 하는데, 혹시 이 부분도 힌트를 주실 수 있나요..? ㅠㅠㅠ

2024-01-26 06:52 UTC, lgyn10 commented on day10/소수찾기.ts
> +  }
`!`를 쓴 것이 코드 리더가 읽기 불편할 수도 있겠다 싶었는데, 오히려 이것 때문에 변수를 하나 더 불필요하게 생성하는 것 보다는 낫겠다 싶어서 사용했습니다!

2024-01-26 07:22 UTC, f-lab-jake requested changes

2024-01-26 07:22 UTC, f-lab-jake commented on day10/소수찾기.ts
> +  }
2부터 n까지 순회하는건 피할수 없죠. 기존에 `boolean[]` 사용했을때도 그렇게 했습니다.
`some`으로 확인할때 모든 `primes`를 확인할 필요가 없습니다. 기존에 써먹었던 좋은 조건인 제곱근까지만 확인하면 된다는걸 빼먹었습니다.

2024-01-26 11:09 UTC, lgyn10 commented on day10/소수찾기.ts
> +    }
드.디.어.!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
문제를 해결했습니다!!!!!!!!!!!!!!!!!
처음에 ` primesToNumSqrt = primes.filter((prime) => prime <= numSqrt)`을 도입한 것은 맞았으나, filter 메서드 자체도 primes가 커지면 시간이 오래걸리더군요.

그래서 `primes[primes.length - 1] <= numSqrt` 이 조건을 생각해내기까지 몇시간이 걸렸네요...허허허허허허헣
어차피 target이 numSqrt가 넘는 시점에는 더 이상 filter메서드가 필요 없기 때문에 이러한 조건문이 시간상의 이점을 크게 가져오더군요!

프로그래머스로 확인해보니, 기존 에라토스테네스의 체를 이용하면 최대 70ms, 59MB를 소모하는데
지금과 같이 공간 효율성을 개선하면 최대 100ms, 39MB를 소모합니다.
공간 복잡도는 획기적으로 줄였지만, 시간 효율성은 조금은 포기해야 하나 봅니다...

만약 비즈니스 로직으로 사용한다면, 메모리 효율이냐, 시간 효율이냐를 놓고 고민을 하겠군요!

아니면 여기에서 시간 효율을 더 개선할 수 있나요...????????🧐

2024-01-26 11:30 UTC, lgyn10 commented on day10/소수찾기.ts
> +    }
`primes[primes.length - 1]` 이거 대신 `target-1`이랑 비교 연산하는 것이 시간 효율이 더 좋네요.. 
이제 어떤 상황에서도 소수찾기5 함수가 시간 및 공간 효율이 좋다고 할 수 있겠군요..!

2024-01-26 11:31 UTC, lgyn10 commented on day10/소수찾기.ts
> +    }
`primes[primes.length - 1]` 이거 대신 `target-1`이랑 비교 연산하는 것이 시간 효율이 더 좋네요.. 
이제 어떤 상황에서도 소수찾기5 함수가 시간 및 공간 효율이 좋다고 할 수 있겠군요..!

이걸로 수정해서 다시 push 했습니당...

2024-01-26 12:32 UTC, lgyn10 commented on day10/소수찾기.ts
> +    }
@f-lab-jake 
개선 사항 없는 것 같으면 따봉주세요! 그럼 머지하겠습니다~

2024-01-29 07:53 UTC, f-lab-jake commented on day10/소수찾기.ts
> +    }
> 처음에  primesToNumSqrt = primes.filter((prime) => prime <= numSqrt)을 도입한 것은 맞았으나, filter 메서드 자체도 primes가 커지면 시간이 오래걸리더군요.

요건 잘못된 설명입니다. 왜그럴까요?

2024-01-29 07:53 UTC, f-lab-jake commented on day10/소수찾기.ts
> +    }
머지는 진행하세요~

2024-01-29 09:23 UTC, merged

2024-01-29 10:24 UTC, lgyn10 commented on day10/소수찾기.ts
> +    }
> 요건 잘못된 설명입니다. 왜그럴까요?

@f-lab-jake 

`console.time()`과 `console.timeEnd()`를 통해 시간 비교를 하면서 분석을 해봤는데요.
음... 설명의 뉘앙스(..?)는 맞으나, 표현상의 문제가 있음을 말씀하시는 것 같습니다...!

`배열의 크기`와 `배열의 길이`는 엄연히 다른 용어로 사용이 되기 때문입니다.
`배열의 크기`는 메모리 상에서 배열이 차지하는 공간을 의미하고, `배열의 길이`는 배열이 가지고 있는 요소의 숫자를 나타냅니다. 
따라서 올바른 설명은 `primes가 커지면`이 아니라
`primes.length가 커지면`
`primes 배열 요소의 수가 커지면`
으로 정정해야 합니다! 

filter 메서드가 오래 걸리는 이유는 순회해야 할 배열의 요소 수가 많아지기 때문이죠!

2024-01-30 02:05 UTC, f-lab-jake commented on day10/소수찾기.ts
> +    }
`filter`는 `primes`의 모든 원소를 다 순회합니다. 그래서 `filter`를 사용하는 것은 시간복잡를 줄여주지 못합니다.
하지만 정말 모든 원소를 다 순회홰야할까요/

2024-01-30 08:19 UTC, lgyn10 commented on day10/소수찾기.ts
> +    }
혼란스럽군요. 

> 처음에 primesToNumSqrt = primes.filter((prime) => prime <= numSqrt)을 도입한 것은 맞았으나, filter 메서드 자체도 primes가 커지면 시간이 오래걸리더군요.

는 잘못된 `설명`이라고 말씀하셨습니다. 즉, **구현한 코드는 맞았다**는 말씀인데요. 제가 확인 질문 드린 부분에 대해서는 답이 없으시니 "아니다"라고 답변하신 것으로 이해됩니다. 
그래서 아직 어떤 부분이 잘못된 설명인지 알지 못합니다. 

그런데, 
> filter는 primes의 모든 원소를 다 순회합니다. 그래서 filter를 사용하는 것은 시간복잡를 줄여주지 못합니다.
하지만 정말 모든 원소를 다 순회홰야할까요?

를 통해 **코드가 잘못됐음**을 말씀하십니다.

```
if (target - 1 <= numSqrt) {
      primesToNumSqrt = primes.filter((prime) => prime <= numSqrt);
    }
```
`하지만 정말 모든 원소를 다 순회홰야할까요?`에 대한 답은 상황에 따라 네, 아니오로 답할 수 있습니다. 
`target - 1 <= numSqrt`인 시점에서는 primes를 다 순회해야 합니다. 
하지만 `target - 1 > numSqrt`인 시점에서는 primes를 한번도 순회할 필요가 없습니다. filter메서드가 동작할 필요가 없어서말이죠.

2024-01-30 08:27 UTC, lgyn10 commented on day10/소수찾기.ts
> +    }
혼란스..럽..네요... 

> 처음에 primesToNumSqrt = primes.filter((prime) => prime <= numSqrt)을 도입한 것은 맞았으나, filter 메서드 자체도 primes가 커지면 시간이 오래걸리더군요.

는 잘못된 `설명`이라고 말씀하셨습니다. 즉, `구현한 코드는 맞았다`는 말씀인데요. 제가 확인 질문 드린 부분에 대해서는 답이 없으시니 "아니다"라고 답변하신 것으로 이해됩니다. 
그래서 아직 어떤 부분이 잘못된 설명인지 알지 못합니다. 

그런데, 
> filter는 primes의 모든 원소를 다 순회합니다. 그래서 filter를 사용하는 것은 시간복잡를 줄여주지 못합니다.
하지만 정말 모든 원소를 다 순회홰야할까요?

를 통해 `코드가 잘못됐음`을 말씀하십니다.

```
if (target - 1 <= numSqrt) {
      primesToNumSqrt = primes.filter((prime) => prime <= numSqrt);
    }
```
`하지만 정말 모든 원소를 다 순회홰야할까요?`에 대한 답은 상황에 따라 네, 아니오로 답할 수 있습니다. 
`target - 1 <= numSqrt`인 시점에서는 primes를 다 순회해야 합니다. 
하지만 `target - 1 > numSqrt`인 시점에서는 primes를 한번도 순회할 필요가 없습니다. filter메서드가 동작할 필요도 없기 때문입니다. 


제가 아무래도 문해력이 많이 약한 것 같습니다.. 멘토님께서 조금 더 친절한 설명을 해주시면 감사드리겠습니다😢

2024-01-30 12:04 UTC, f-lab-jake commented on day10/소수찾기.ts
> +    }
일단 구현도 잘못됐고(제가 의도한 모범답안이 아니고) 제가 설명이 틀렸다고 한건 `primesToNumSqrt = primes.filter((prime) => prime <= numSqrt)을 도입한 것은 맞았으나` 요부분부터 잘못됐단 얘기였습니다. 어디서부터 다시 생각해야하는 지를 짚은 것인데 다시 보니 오해하실만 한 것 같습니다. 좀더 자세히 안내할게요.

모범답안은 https://www.geeksforgeeks.org/lodash-_-takewhile-method/ 요 함수를 보면 힌트를 얻을 수 있을겁니다.

2024-01-30 15:33 UTC, lgyn10 commented on day10/소수찾기.ts
> +    }
<img width="916" alt="스크린샷 2024-01-30 오후 11 32 10" src="https://github.com/f-lab-edu/alg-everyday/assets/72643542/8d8feb4a-38a2-46b5-a0f7-87955a8cd090">

소수찾기 문제가 굉장히 흥미롭군요. 

```ts
// 기존 코드
for (let target = 2; target <= n; target++) {
    if (!primes.some((prime) => target % prime === 0)) primes.push(target);
    } ...
```
> some으로 확인할때 모든 primes를 확인할 필요가 없습니다. 기존에 써먹었던 좋은 조건인 제곱근까지만 확인하면 된다는걸 빼먹었습니다.

위의 피드백을 통해 `if (target - 1 <= numSqrt) { ... }` 를 생각해낼 수 있었습니다. 

>filter는 primes의 모든 원소를 다 순회합니다. 그래서 filter를 사용하는 것은 시간복잡를 줄여주지 못합니다.
하지만 정말 모든 원소를 다 순회홰야할까요?

위의 피드백을 통한 힌트를 참고하여 `primesToNumSqrt = takeWhile(primes, (prime) => prime <= numSqrt);` 이와 같은 코드를 작성할 수 있습니다. 

따라서, 제가 생각하는 모범 답안은 다음과 같습니다. `6th sol`
공간효율성을 고려한 코드 중 제일 시간효율이 좋습니다. 
```ts
const 소수찾기6 = (num: number) => {
  const primes: number[] = [];
  const numSqrt = Math.sqrt(num);
  let primesToNumSqrt: number[] = [];
  for (let target = 2; target <= num; target++) {
    if (target - 1 <= numSqrt) {
      primesToNumSqrt = takeWhile(primes, (prime) => prime <= numSqrt);
    }
    if (!primesToNumSqrt.some((prime) => target % prime === 0))
      primes.push(target);
  }
  return primes.length;
};
```

하지만, 여기에서 시간효율성을 좀 포기하고 `let primesToNumSqrt: number[] = [];`이라는 변수제거를 통해 코드 가독성을 높이면 다음과 같습니다. `8th sol`
저 변수 제거를 통해 공간효율성을 더 챙길 수 있는지는 잘 모르겠습니다.. 
```ts
const 소수찾기8 = (num: number) => {
  const primes: number[] = [];
  const numSqrt = Math.sqrt(num);
  for (let target = 2; target <= num; target++) {
    if (
      !takeWhile(primes, (prime) => prime <= numSqrt).some(
        (prime) => target % prime === 0,
      )
    )
      primes.push(target);
  }
  return primes.length;
};
```

따라서 다음과 같이 결론을 지었습니다.

1. 시간효율성만을 최대로 고려한다면 에라토스테네스의 체를 적용한 `3th sol`코드를 채택한다. 
2. 시간효율성과 공간효율성을 모두 챙긴다면 `6th sol`코드를 채택한다.
3. `7th sol`코드와 `8th sol`코드를 통해, `takeWhile()`의 시간 효율성이 어마무시함을 알 수 있다. 

`새로 수정한 코드는 다시 pr올렸습니다. 추후 본 내용을 다시 들여다보기 편하게 여기에 커멘트를 남깁니다.`