12/29 문제 풀이 (4th)
f-lab-edu/alg-everyday pull request #2
Opened 2023-12-29 06:03 UTC by lgyn10

2023-12-30 05:55 UTC, f-lab-jake requested changes

2023-12-30 05:55 UTC, f-lab-jake commented on lv1-자연수뒤집어배열로만들기.js
> +  [...String(n)].map((v, i) => arr.unshift(parseInt(v)));
이럴땐 map을 쓰지맙시다
- return값을 활용하지않을때
- map 안에서 변경이 일어날때(이경우엔 `arr.unshift`)

2023-12-30 05:55 UTC, f-lab-jake commented on lv1-자연수뒤집어배열로만들기.js
> +  [...String(n)].map((v, i) => arr.unshift(parseInt(v)));
이유도 생각해봅시다.

2023-12-30 05:55 UTC, f-lab-jake commented on lv1-정수내림차순으로배치하기.js
> +      .map((v) => parseInt(v))
`.map(parseInt)`라고 써도 됩니다. 왜그럴까요?

2023-12-30 05:55 UTC, f-lab-jake commented on lv1-자릿수더하기.js
> +  return [...String(n)].reduce((a, b) => parseInt(a) + parseInt(b), 0);
지금보면 `a`는 숫자인데도 거기다가 `parseInt`를 하고 있습니다. 숫자넣으면 그대로 나오니까 결국 답이 나오긴 하는데 이런 동작에 의존하면 안좋습니다.

2023-12-30 05:55 UTC, f-lab-jake commented on lv1-음양더하기.js
> +    else return acc - curVal;
숨겨진 중복을 제거해보세요.

2023-12-30 05:55 UTC, f-lab-jake commented on lv1-문자열내p와y의개수.js
> +  let ans = [...s].forEach((v, i) => {
`ans`에는 무슨 값이 담기나요?

2023-12-30 05:55 UTC, f-lab-jake commented on lv1-문자열내p와y의개수.js
> +  return pNum === yNum ? true : false;
자명한 실수입니다.

2023-12-30 05:55 UTC, f-lab-jake commented on lv1-나누어떨어지는숫자배열.js
> +  });
`push` 하지말고 풀어봆디ㅏ.

2023-12-30 05:55 UTC, f-lab-jake commented on lv1-x만큼간격이있는n개의숫자.js
> +    ans.push(ans[ans.length - 1] + x);
`ans[ans.length - 1]`는 `ans.at(-1)`로 쓸수 있습니다.

그런데 그냥 `ans` 요소의 값을 참조하지 않는 방법으로 짜봅시다.

2023-12-31 05:45 UTC, f-lab-jake commented on lv1-정수내림차순으로배치하기.js
> +      .map((v) => parseInt(v))
아 맞습니다. 깜빡했네요. 숨겨진 index 인자때문에 `parseInt`를 아쉽게도 못쓰죠. 그래서 `Number`를 써야합니다. 의미상은 `parseInt`가 더 맞긴하지만 말이죠.

일반적으로 `(x) => f(x)`는 `f`로 줄여쓸수 있습니다. 다만 지금처럼 숨겨진 인자가 더 있을때 곤란한 동작이 나옵니다.

2023-12-31 05:46 UTC, f-lab-jake commented on lv1-자릿수더하기.js
> +  return [...String(n)].reduce((a, b) => parseInt(a) + parseInt(b), 0);
변수명과는 무관합니다. `acc`나 `a`나 별차이 없으니 그부분은 괜찮습니다. 숫자에다가 다시 `parseInt`를 하고있는게 잘못됐다는 얘깁니다.

2023-12-31 05:47 UTC, f-lab-jake commented on lv1-문자열내p와y의개수.js
> +  return pNum === yNum ? true : false;
그냥 `return pNum === yNum` 하면 된단 얘기였습니다.
오히려 `count`같은 변수는 코드를 이해하기 어렵게 만듭니다.

2023-12-31 05:47 UTC, f-lab-jake commented on lv1-x만큼간격이있는n개의숫자.js
> +    ans.push(ans[ans.length - 1] + x);
곱하기도 하지 말아보세요.

2023-12-31 05:49 UTC, f-lab-jake commented on lv1-자연수뒤집어배열로만들기.js
> +  [...String(n)].map((v, i) => arr.unshift(parseInt(v)));
1번은 말씀하신 이유가 맞습니다. 그런데 다른 이유도 있습니다.
2번에 대해선 멘토링 시간에 자세히 설명하죠.

2023-12-31 07:00 UTC, lgyn10 commented on lv1-자연수뒤집어배열로만들기.js
> +  [...String(n)].map((v, i) => arr.unshift(parseInt(v)));
넵!

2023-12-31 07:00 UTC, lgyn10 commented on lv1-정수내림차순으로배치하기.js
> +      .map((v) => parseInt(v))
넵

2023-12-31 07:02 UTC, lgyn10 commented on lv1-자릿수더하기.js
> +  return [...String(n)].reduce((a, b) => parseInt(a) + parseInt(b), 0);
넵 그런 의미로 생각은 했었는데, 정확한 코멘트를 하지 못했네요..

2023-12-31 07:02 UTC, lgyn10 commented on lv1-문자열내p와y의개수.js
> +  return pNum === yNum ? true : false;
넵

2023-12-31 07:14 UTC, lgyn10 commented on lv1-x만큼간격이있는n개의숫자.js
> +    ans.push(ans[ans.length - 1] + x);
새로 커밋했습니다!

2023-12-31 13:14 UTC, f-lab-jake approved these changes

2023-12-31 14:23 UTC, merged