day12
f-lab-edu/alg-everyday pull request #21
Opened 2024-02-02 07:02 UTC by lgyn10

올바른 괄호 문제와 파일명정렬 문제 풀었습니다.

파일명 정렬의 경우 `forProgrammers` 파일 코드는 프로그래머스 채점용으로 리펙토링이 되지 않았습니다. 

그렇기 때문에, `파일명정렬lodash` 코드만 봐주시면 될 것 같습니다.

2024-02-02 13:30 UTC, f-lab-jake requested changes

2024-02-02 13:30 UTC, f-lab-jake commented on day12/올바른괄호.ts
> +  return ans;
더 간결하고 효율적으로 고쳐봅시다. 힌트는 `ans`를 그냥 없애는 것입니다.

2024-02-02 14:41 UTC, lgyn10 commented on day12/올바른괄호.ts
> +};
`(1)`처럼도 접근해봤는데, 간결이랑은 거리가 멀어지고, ans 변수를 다르게 쓸 뿐 변수를 줄이지는 못하는 방법이더군요. 
`(2)`는 가장 기본이 되는 for of 문으로 풀어봤는데요. 오늘 이터러블 공부 안 했으면 이 방법은 못 떠올렸을 것 같습니다. `(1)`보다 시간 효율도 좋고, 변수도 `cnt`만 쓰니 공간 효율도 좋을 것 같습니다.

2024-02-02 16:10 UTC, f-lab-jake approved these changes

2024-02-02 16:21 UTC, lgyn10 commented
@f-lab-jake 
사실 `올바른괄호` 문제보다도 `파일명정렬`에 대한 커멘트를 많이 기대했는데요. 
커멘트가 없으시니 아쉬운 부분 없이 깔끔하게 풀었다고 이해하면 될까요..?

2024-02-02 16:21 UTC, merged

2024-02-03 05:18 UTC, lgyn10 commented on day12/파일명정렬lodash.ts
> +  });
이 부분에서 `map`함수가 순수 함수로만 쓰이지 않고, 부수 효과를 발생시키는데요. `customWordsFile`에 할당하는 리턴값의 메모리 주소를 `fileMap`과 `filesWithCustomWords`이 공유해야 하기 때문에 불가피하다고 생각했습니다. 

이 부분에서 map 함수를 순수함수로만 구현하는 방향으로 개선을 할 수도 있을 것 같은데, 음... 같은 메모리 주소를 바라봐야 한다는 점 때문에 지금 코드가 안전하지 않을까 싶습니다...!

2024-02-03 05:18 UTC, lgyn10 commented on day12/파일명정렬lodash.ts
> +  );
사실 변수명이 조금 친철하지 않은데요. 변수명만 봐서는 어떻게 정렬을 의도하는지 알기 어려울 것 같습니다. 또한, 함수 구현 부분도 어떤 로직을 구현하고 싶은지 코드만으로는 알아보기가 좀 어렵다..?(사실 제가 이 코드 막상 써놓고 왜 잘 동작하는지 이해하는데 좀 걸렸습니다...ㅎ) 정도입니다. 

개선을 한다면, `HEAD` 정렬 부분과 `NUMBER` 정렬 부분을 분리해서 구현하는 방법이 있을 것 같네요!