dat14
f-lab-edu/alg-everyday pull request #24
Opened 2024-02-05 03:42 UTC by lgyn10

실패율 문제를 풀었습니다.
https://school.programmers.co.kr/learn/courses/30/lessons/42889

매핑하는 부분에서 `string` 또는 `number`는 같은 값이면 같은 메모리 주소를 바라보기 때문에, `[ ]` 로 감싸줌으로써 각각의 요소가 각각의 매모리 주소를 가지도록 처리했습니다.
코어 자바스크립트 1장 데이터 타입 공부를 통해 이 부분에서 왜? 에 대한 답을 할 수 있군요!

2024-02-05 10:18 UTC, f-lab-jake requested changes

2024-02-05 10:18 UTC, f-lab-jake commented on day14/실패율.ts
> +  const yetClearedUsersNumArr = Array(N + 1).fill(0);
`yetClearedUserCounts` 쯤으로 하면 되겠네요. 지금부터 arr을 변수명에서 뺍시다.

2024-02-05 10:18 UTC, f-lab-jake commented on day14/실패율.ts
> +  const failRateArr = yetClearedUsersNumArr.map((v, idx) => {
시간복잡도가 얼마죠? 더 효율적으로 개선해봅시다.

2024-02-05 10:26 UTC, lgyn10 commented on day14/실패율.ts
> +  const yetClearedUsersNumArr = Array(N + 1).fill(0);
앞으로의 코드들은 `arr`을 빼도록 하겠습니다!

2024-02-05 10:55 UTC, lgyn10 commented on day14/실패율.ts
> +  const failRateArr = yetClearedUsersNumArr.map((v, idx) => {
`yetClearedUsersNumArr`을 모두 순회하고 이후 slice메서드에서도 `yetClearedUsersNumArr`을 다시 순회하기 때문에 `O(n^2)`입니다.

slice 메서드를 사용 하지 않는 방법으로 코드를 수정했습니다~!

2024-02-06 01:10 UTC, lgyn10 commented on day14/실패율tuple.ts
> +  });
피드백을 반영하여 튜플타입으로 선언하고 sort 메서드의 콜백함수를 다시 정의해서 문제를 풀었습니다. 

질문이 있는데요. 이번과 같이 코드 수정을 하는 이유에 대해서 좀 궁금합니다. 
공간효율이나 시간효율 측면에서는 map 코드와 tuple 코드의 차이가 유의미하지 않다고 생각하는데요.
그러면 이번 코드 수정은 `map을 사용하지 않고 구현해보는 것`에 의의가 있는건지, `코드 가독성 측면의 향상`에 있는지 여쭤봅니당

개인적으로는 `시간 및 공간 효율의 차이는 유의미하지 않기 때문에, 코드 가독성을 높이고 불필요한 변수 선언을 방지한다` 로 생각합니다.

2024-02-06 01:17 UTC, f-lab-jake approved these changes

2024-02-06 01:19 UTC, f-lab-jake commented on day14/실패율tuple.ts
> +  });
Map이 완전히 O(1)이 아니므로 n이 커지면 유의미한 차이가 생깁니다.
그리고 가독성 측면에서도 훨씬 낫습니다. 처음 코드는 왜 그게 돌아가는지 이해하기가 어렵습니다. 안돌아가는 부분을 또다른 트릭(`[]`)으로 해결하고 있어 더더욱 어렵죠.

2024-02-06 01:40 UTC, lgyn10 commented on day14/실패율tuple.ts
> +  });
넵! Map이 해시 자료 구조라고 언뜻 들었었는데, 예전 알고리즘 공부 자료에 해시 테이블 충돌에 관한 내용이 있어 다시 읽어보고 왔습니다.

피드백 감사합니다~!

2024-02-06 01:40 UTC, merged

2024-02-06 02:24 UTC, f-lab-jake commented on day14/실패율tuple.ts
> +  });
실제로 측정해보면 적당한 N에서도 차이가 나는걸 확인할수있을겁니다