day16
f-lab-edu/alg-everyday pull request #26
Opened 2024-02-09 14:47 UTC by lgyn10

2024-02-10 15:24 UTC, f-lab-jake requested changes

2024-02-10 15:24 UTC, f-lab-jake commented on day16/프로세스.ts
> +    const maxQueue = maxBy(tuplesQueue, 0)![0];
요건 `maxPriority`가 맞겟죠?

2024-02-10 15:24 UTC, f-lab-jake commented on day16/프로세스.ts
> +    );
문제 설명에 따라 짜면 이렇게 됩니다. 요것도 괜찮습니다.
근데 `shift`연산이 좀 비효율적입니다. `shift`를 안쓰고 짜봅시다.

2024-02-10 15:24 UTC, f-lab-jake commented on day16/프로세스.ts
> +  while (tuplesQueue.length > 0) {
끝까지 다 돌필요 없죠?

2024-02-11 05:51 UTC, lgyn10 commented on day16/프로세스.ts
> +    const maxQueue = maxBy(tuplesQueue, 0)![0];
넵, 맞습니다. 변수명에 의미를 확실하게 부여하겠습니다!

2024-02-12 01:58 UTC, lgyn10 commented on day16/프로세스.ts
> +    );
`shift` 연산이 O(n) 시간 복잡도를 가지기 때문에 비효율이라고 이해됩니다. 
`shift`와 `push` 메서드로 큐 동작을 구현한건데요.
큐 동작은 유지하면서, 다른 코드 표현으로 코드를 짜보라는 말씀이신가요? 
아니면, 큐 동작과 상관 없이 다른 방향으로 접근해서 짜보라는 말씀이신가요?

2024-02-12 01:58 UTC, lgyn10 commented on day16/프로세스.ts
> +  while (tuplesQueue.length > 0) {
넵, 반복문을 쓸 때, 꼭 다 순회해야하는지 한 번 생각하는 과정을 놓치지 않겠습니다.

2024-02-12 03:04 UTC, lgyn10 commented on day16/프로세스.ts
> +  while (last(orderedQueue) !== locTuple) {
orderedQueue의 마지막 요소가 찾고자 하는 `locTuple`의 값과 같아지면 더 이상 반복문을 돌 필요가 없게 수정했습니다.

2024-02-12 03:04 UTC, lgyn10 commented on day16/프로세스.ts
> +};
반복문에서 매번 O(n)인 `shift` 연산을 하는 대신, `reversedTuplesQueue`를 선언하여 필요할 때만 O(n)인 `unshift` 연산을 하도록 시간 효율을 개선 시켰습니다.

2024-02-12 09:42 UTC, bglgwyng requested changes

2024-02-12 09:42 UTC, bglgwyng commented on day16/프로세스.ts
> +    const elementToBoConfirmed = reversedTuplesQueue.pop();
애초에 `pop`을 하는걸 피해보란 얘기였습니다. `unshift`도 마찬가지로 비효율적입니다.

2024-02-12 09:42 UTC, bglgwyng commented on day16/프로세스.ts
> +  const orderedQueue: number[][] = [];
요건 `[number, number][]` 타입을 가져야합니다

2024-02-12 09:42 UTC, bglgwyng commented on day16/프로세스.ts
> +    const maxPriority = head(maxBy(reversedTuplesQueue, 0));
`head`는 배열을 첫원소를 구하는 것입니다. 그런데 이 경우엔 js array이긴하지만 의미상 배열이 아니라 튜플입니다. 그냥 인덱스로 빼던가 destructuring을 하세요.

2024-02-13 04:32 UTC, lgyn10 commented on day16/프로세스.ts
> +  const orderedQueue: number[][] = [];
`[number, number][]` 이렇게 표현해야 비로소 튜플 타입임을 명시하는 건가요?

2024-02-13 08:46 UTC, lgyn10 commented on day16/프로세스.ts
> +  const orderedQueue: [number, number][] = [];
먼저, 
> 요건 [number, number][] 타입을 가져야합니다

에 대해서 수정하였습니다.

2024-02-13 08:46 UTC, lgyn10 commented on day16/프로세스.ts
> +    const maxPriority = maxBy(tuplesQueue, 0)![0];
기존 ` const maxPriority = head(maxBy(reversedTuplesQueue, 0));` 에서 
>head는 배열을 첫원소를 구하는 것입니다. 그런데 이 경우엔 js array이긴하지만 의미상 배열이 아니라 튜플입니다. 그냥 인덱스로 빼던가 destructuring을 하세요.

을 반영하여 인덱스로 값을 꺼냈습니다.

2024-02-13 08:46 UTC, lgyn10 commented on day16/프로세스.ts
> +    (elementToBoConfirmed![0] === maxPriority ? orderedQueue : tuplesQueue).push(elementToBoConfirmed!);
이 부분에서 헤매고 있는데요. 

> 문제 설명에 따라 짜면 이렇게 됩니다. 요것도 괜찮습니다.
근데 shift연산이 좀 비효율적입니다. shift를 안쓰고 짜봅시다.

에 대해서 좀 더 힌트가 필요할 것 같습니다.

2024-02-13 11:41 UTC, f-lab-jake approved these changes

2024-02-13 11:41 UTC, f-lab-jake commented on day16/프로세스.ts
> +    (elementToBoConfirmed![0] === maxPriority ? orderedQueue : tuplesQueue).push(elementToBoConfirmed!);
앗 죄송합니다. 이거 제가 문제를 좀 잘못 읽었네요.
지금 풀이가 거의 최선이 맞습니다.

2024-02-13 12:36 UTC, lgyn10 commented on day16/프로세스.ts
> +    (elementToBoConfirmed![0] === maxPriority ? orderedQueue : tuplesQueue).push(elementToBoConfirmed!);
넵

2024-02-13 12:36 UTC, lgyn10 commented on day16/프로세스.ts
> +    (elementToBoConfirmed![0] === maxPriority ? orderedQueue : tuplesQueue).push(elementToBoConfirmed!);
넵

2024-02-13 12:37 UTC, merged