day17
f-lab-edu/alg-everyday pull request #27
Opened 2024-02-10 07:29 UTC by lgyn10

2024-02-10 07:31 UTC, lgyn10 commented
주식가격 문제의 경우
`주식가격array` 코드는 채점에서 시간 초과가 났습니다. 
`주식가격stack` 코드를 통해서 시간효율성을 개선시켰습니다.

2024-02-12 09:44 UTC, bglgwyng requested changes

2024-02-12 09:44 UTC, bglgwyng commented on day17/주식가격stack.ts
> +  const noDropSeconds = (selectedPrice: number, idx: number) => {
`idx`인자 빼고 `slice`를 활용해서 시간초과나는지 확인해볼까요? 될수도 있고 안될수도 있습니다.

2024-02-13 12:32 UTC, lgyn10 commented on day17/주식가격stack.ts
> +  const noDropSeconds = (selectedPrice: number, idx: number) => {
@f-lab-jake 
`idx` 인자 없이 `slice`를 어떻게 활용해야할지 감이 안 잡히는데요.
`주식가격array` 풀이에서도 `slice`를 활용했는데,  `idx`를 인자로 필요로 한 풀이였습니다. 

어떤 방향의 풀이인지 풀어서 말씀 주시면 감사하겠습니다.

2024-02-13 16:13 UTC, f-lab-jake commented on day17/주식가격stack.ts
> +  const noDropSeconds = (selectedPrice: number, idx: number) => {
요렇게 하고 `noDropSeconds(prices: number[]): number` 요렇게 정의하고
아래에서
`prices.map((price, idx) => noDropSeconds(price.slice(idx)))` 요렇게 호출해보세요

2024-03-07 07:25 UTC, lgyn10 commented on day17/주식가격stack.ts
> +};
>idx인자 빼고 slice를 활용해서 시간초과나는지 확인해볼까요? 될수도 있고 안될수도 있습니다.

>요렇게 하고 noDropSeconds(prices: number[]): number 요렇게 정의하고
아래에서
prices.map((price, idx) => noDropSeconds(price.slice(idx))) 요렇게 호출해보세요

위의 피드백을 받아 코드 수정을 해봤습니다. 말씀하셨듯이 `silce`를 사용하니 프로그래머스 채점에서는 시간초과가 나더군요! 

그럼 day17은 머지해도 될까요??!?

2024-03-07 07:46 UTC, f-lab-jake commented on day17/주식가격stack.ts
> +};
넵 머지합시다. 이 경우엔 `slice`에서 실제로 copy가 일어나나 보네요. 쨋든 copy없이 `slice`할수 있는 언어들이 있고, `slice`가 더 의미를 잘 나타내는것만 일단 인지하고 계심됩니다.

2024-03-07 08:24 UTC, merged