day18
f-lab-edu/alg-everyday pull request #28
Opened 2024-02-11 05:42 UTC by lgyn10

Map을 사용하여 문제 해결
프로그래머스 채점 통과!

2024-02-11 06:28 UTC, f-lab-jake requested changes

2024-02-11 06:28 UTC, f-lab-jake commented on day18/완주하지못한선수.ts
> +    names.forEach(name => map.set(name, (map.get(name) || 0) + 1));
`||` 대신 `??`를 쓰세요

2024-02-11 06:28 UTC, f-lab-jake commented on day18/완주하지못한선수.ts
> +    names.forEach(name => map.set(name, (map.get(name) || 0) + 1));
그리고 `forEach`를 밖으로 빼고 이름 하나에 대해서만 동작하는 함수로 정의해보세요

2024-02-12 03:05 UTC, lgyn10 commented on day18/완주하지못한선수.ts
> +    names.forEach(name => map.set(name, (map.get(name) || 0) + 1));
`??` 쓰겠습니다!

>  forEach를 밖으로 빼고 이름 하나에 대해서만 동작하는 함수로 정의해보세요
이게 어떤 말씀인지, 좀 이해하기 어렵습니다...! 좀 더 풀어서 말씀 주시면 감사하겠습니다.

2024-02-12 13:20 UTC, f-lab-jake commented on day18/완주하지못한선수.ts
> +    names.forEach(name => map.set(name, (map.get(name) || 0) + 1));
`(map: Map<string, number>, name: string) => void` 요 타입을 갖도록 고쳐보세요

2024-03-07 10:46 UTC, lgyn10 commented on day18/완주하지못한선수.ts
> +};
> forEach를 밖으로 빼고 이름 하나에 대해서만 동작하는 함수로 정의해보세요
> (map: Map<string, number>, name: string) => void 요 타입을 갖도록 고쳐보세요

위의 피드백을 적용하여 코드 수정했습니다! 
근데, `forEach`를 밖으로 뺀 것은 `cmpNameMapping` 함수명에서 기대할 수 있는 로직 만을 남겨두기 위함인가요?
어떤 이유에서 `forEach`를 분리하는 건가요??

2024-03-07 11:46 UTC, f-lab-jake approved these changes

2024-03-07 11:46 UTC, f-lab-jake commented on day18/완주하지못한선수.ts
> +};
`runners.forEach(name => cntNameMapping(runnersMap, name));` 요걸
`runners.forEach(cntNameMapping.bind(null, runnersMap));` 요렇게 쓸수있고요.
`cntNameMapping`의 정의를 좀 바꾸면
`runners.forEach(cntNameMapping(runnersMap));`로 쓸수 있겠죠.
자이제 `cntNameMapping`의 이름을 사실 `increase`로 바꿀수있단걸 알게됩니다.
`Map`을 확장해서 `increase`같은 메서드를 포함하게하면
`runners.forEach(runnersMap.increase);`로 쓸수도 있겠죠.
함수를 최대한 작게 만들고 조합하는 방법을 배우란 취지에서 이 변경을 하게했습니다.

2024-03-08 11:37 UTC, lgyn10 commented on day18/완주하지못한선수-currying.ts
> +};
> runners.forEach(name => cntNameMapping(runnersMap, name)); 요걸
runners.forEach(cntNameMapping.bind(null, runnersMap)); 요렇게 쓸수있고요.
cntNameMapping의 정의를 좀 바꾸면
runners.forEach(cntNameMapping(runnersMap));로 쓸수 있겠죠.

이 피드백을 통해 `커링` 개념을 적용해서 리펙토링을 해보았습니다!

2024-03-08 11:37 UTC, lgyn10 commented on day18/완주하지못한선수-Map확장.ts
> +}
>자이제 cntNameMapping의 이름을 사실 increase로 바꿀수있단걸 알게됩니다.
Map을 확장해서 increase같은 메서드를 포함하게하면
runners.forEach(runnersMap.increase);로 쓸수도 있겠죠.

`ExtendedMap` 클래스를 정의해서 `increase` 메서드를 사용할 수 있게 리펙토링해보았습니다!

2024-03-08 11:37 UTC, lgyn10 commented on day18/완주하지못한선수-currying.ts
> +};
@f-lab-jake 
`커링`이라는 개념을 들어보기만 해서 처음 써보네요. 혹시 잘 못 사용한 부분이 있다면 말씀해주세요!

2024-03-08 11:37 UTC, lgyn10 commented on day18/완주하지못한선수-Map확장.ts
> +}
@f-lab-jake 
Map을 확장할 생각을 못했는데, 이런 식으로도 구현이 가능하군요. 잘 못 구현한 부분이 있다면 말씀해주세요!

2024-03-09 01:50 UTC, f-lab-jake approved these changes

2024-03-09 01:50 UTC, f-lab-jake commented on day18/완주하지못한선수-Map확장.ts
> +}
넵, 이렇게하는게 맞습니다. 특히 `this` 문제 때문에 `increase =` 식으로 정의해야하는데 알아서 잘 했군요.

사실 문제하나 푸는데는 좀 오버킬이긴한데 핵심은 함수를 최대한 작게 만들고 조합하라는 겁니다.

2024-03-09 10:35 UTC, lgyn10 commented on day18/완주하지못한선수-Map확장.ts
> +}
말씀대로 `함수를 최대한 작게 만들고 조합한다` 라는 취지로는 너무 좋은 피드백이였습니다!

2024-03-09 10:36 UTC, merged