12/30 문제풀이(2nd)
f-lab-edu/alg-everyday pull request #3
Opened 2023-12-30 15:24 UTC by lgyn10

2023-12-31 03:51 UTC, f-lab-jake requested changes

2023-12-31 03:51 UTC, f-lab-jake commented on lv1-가운데글자가져오기.js
> +  return len % 2 == 0 ? s.charAt(len / 2 - 1) + s.charAt(len / 2) : s.charAt(Math.ceil(len / 2) - 1);
중복을 제거해봅시다.

2023-12-31 03:51 UTC, f-lab-jake commented on lv1-내적.js
> +  a.forEach((v, i) => (ans += v * b[i]));
lodash의 `zip`을 활용해봅시다.

2023-12-31 06:49 UTC, lgyn10 commented on lv1-가운데글자가져오기.js
> +}
중복을 제거해봤습니다!

2023-12-31 06:49 UTC, lgyn10 commented on lv1-내적.js
> +}
lodash 라이브러리의 zip함수를 활용해봤습니다!

2024-01-01 11:53 UTC, f-lab-jake commented on lv1-내적.js
> +}
딱 `zip`만 적용하고 끝내지 말고, 그걸통해 어떤 개선을 더 할수있게 되엇는지를 생각하고 적용합시다.

2024-01-01 11:53 UTC, f-lab-jake commented on lv1-가운데글자가져오기.js
> +}
일단 자명하게, `len / 2`라는 중복이 여전히 있습니다.

2024-01-01 12:56 UTC, lgyn10 commented on day2/lv1-가운데글자가져오기.js
> +}
전체적으로 길게 표현된 삼항 연산자를 묶어 가독성이 늘었습니다

2024-01-01 12:56 UTC, lgyn10 commented on day2/lv1-내적.js
> +}
`let ans = 0;`이라는 불필요한 변수 사용을 지우고, reduce를 이용해 한줄로 표현 가능해졌습니다

2024-01-02 04:54 UTC, f-lab-jake commented on day2/lv1-가운데글자가져오기.js
> +}
`Math.floor`가 있습니다.

2024-01-02 15:08 UTC, lgyn10 commented on day2/lv1-가운데글자가져오기.js
> +}
`Math.floor`사용과 문자를 가져오는 법을 바꿔보았습니다.

2024-01-02 23:56 UTC, f-lab-jake requested changes

2024-01-02 23:56 UTC, f-lab-jake commented on day2/lv1-가운데글자가져오기.js
> +  let halfLen = Math.floor((len - 1) / 2);
`floor`의 의미가 뭔가요? 혹시 맞는 답이 나올때까지 코드를 이리저리 수정한 결과가 이것인가요?

2024-01-02 23:57 UTC, f-lab-jake commented on day2/lv1-가운데글자가져오기.js
> +}
처음 `slice`쓴게 더 좋다고 생각합니다. 약간 더 고치면
`s.slice(halfLen + len % 2 + 1)`
있다 멘토링에서 마저 설명하죠

2024-01-03 04:16 UTC, lgyn10 commented on day2/lv1-가운데글자가져오기.js
> +}
오..... 와....... 훨씬 깔끔해지네요..!

2024-01-04 13:54 UTC, f-lab-jake requested changes

2024-01-04 13:54 UTC, f-lab-jake commented on day2/lv1-가운데글자가져오기.js
> +  let mid = Math.floor((len - 1) / 2);
`let mid = Math.floor(len / 2) - (len % 2 ? 1 : 0)`
요런 방식이 약간 길지만 더 낫습니다. 
> 짝수면 1을 뺀다

란 의미가 명확히 전달 되니까요. 지금 코드도 같은 결과를 주긴 하는데 `(len - 1)` 여기서 -1의 정체가 뭔지를 고민해야합니다.
`isOdd` 정도의 변수를 도입해서 고쳐봅시다.

2024-01-04 13:54 UTC, f-lab-jake commented on day2/lv1-가운데글자가져오기.js
> +  return s.slice(mid, mid + 1 + !(len % 2));
`!(len % 2)`도 비슷한 이유로 안 좋습니다. 차라리 `len % 2 ? 1 : 0`이 낫습니다.
boolean과 number 사이에 정의된 + 연산같은건 안쓰는게 좋습니다.

2024-01-05 23:07 UTC, closed without merging