day20
f-lab-edu/alg-everyday pull request #30
Opened 2024-03-09 11:10 UTC by lgyn10

2024-03-09 11:14 UTC, lgyn10 commented on day20/전화번호목록.ts
> +// https://school.programmers.co.kr/learn/courses/30/lessons/42577
@f-lab-jake 
전화번호목록 문제가 해시를 이용해서 푸는 문제로 프로그래머스에서는 소개가 되었는데요...!

이 문제를 해시로 푸는 접근법을 잘 모르겠더라구요. 혹시 멘토님께서는 접근법이 보이시나요...? 
아니면, 이 문제를 굳이 해시로 풀어봐야할 문제가 아닌걸까요..?

2024-03-11 00:55 UTC, f-lab-jake commented on day20/전화번호목록.ts
> +// https://school.programmers.co.kr/learn/courses/30/lessons/42577
정렬을 사용하지 않는 방법이 있습니다. 그게 더 효율적인건 아닙니다. 그 방법을 일단 찾아보고 비교해보세요.

2024-03-12 04:18 UTC, lgyn10 commented on day20/전화번호목록.ts
> +};
참조 코드를 찾아보고, `Map` 객체를 사용하도록 리펙토링해보았습니다!

말씀주신대로, `sort()`를 이용한 코드보다 시간 및 공간 측면에서 효율성이 떨어지는 것을 확인했습니다.
프로그래머스 채점에서는 통과는 되기는 하더군요.

해시맵을 이용한 경우는 이중 for문이 있기에 `sort()`처럼 한번만 순회하는 경우보다 효율성이 떨어진다고 생각합니다!

2024-03-12 10:38 UTC, f-lab-jake requested changes

2024-03-12 10:38 UTC, f-lab-jake commented on day20/전화번호목록.ts
> +};
`startsWith`을 쓰면 좀더 깔끔하게 할수 있습니다

2024-03-13 11:56 UTC, merged