Day21
f-lab-edu/alg-everyday pull request #31
Opened 2024-03-10 08:05 UTC by lgyn10

2024-03-11 00:53 UTC, f-lab-jake requested changes

2024-03-11 00:53 UTC, f-lab-jake commented on day21/의상.ts
> +const 의상 = (clothes: string[][]): number => {
튜플타입 `[string, string][]`을 사용하세요.
아래 코드들도 거기에 맞춰 바꾸세요.
튜플타입과 배열타입은 어떻게 다를까요?

2024-03-11 00:53 UTC, f-lab-jake commented on day21/짝수홀수개수.ts
> +  forEach(numList, (n) => (n % 2 === 0 ? evenCnt++ : oddCnt++));
반환값을 사용하지 않을때는 삼항연산자 대신 if를 쓰세요

2024-03-12 02:51 UTC, lgyn10 commented on day21/의상.ts
> +const 의상 = (clothes: string[][]): number => {
해당 문제에서는 `[string, string][]`와 같은 배열 구조여서 튜플의 장점을 살리기는 쉽지 않지만, `[string, number][]`와 같은 자료구조라면
배열 타입에서는 `string | number[][]`와 같이 타입 지정을 하게됩니다.
이를 튜플 타입으로  `[string,number][]`처럼 타입을 지정하면, 타입 검사를 더 강하게 해줌으로서 에러를 방지해줄 수 있다고 생각합니다!

2024-03-12 02:52 UTC, lgyn10 commented on day21/짝수홀수개수.ts
> +  forEach(numList, (n) => (n % 2 === 0 ? evenCnt++ : oddCnt++));
넵!

2024-03-12 10:36 UTC, f-lab-jake approved these changes

2024-03-13 11:56 UTC, merged