Day23
f-lab-edu/alg-everyday pull request #33
Opened 2024-03-15 12:36 UTC by lgyn10

2024-03-16 04:53 UTC, f-lab-jake requested changes

2024-03-16 04:53 UTC, f-lab-jake commented on day23/세균증식.ts
> +    cnts = multiply(cnts, 2);
요렇게는 잘 안합니다.
`multiply`같은건 `map(xs, multiply)` 이럴때 유용합니다

2024-03-16 04:53 UTC, f-lab-jake commented on day23/짝수는싫어요.ts
> +  for (let i = 1; i <= n; i += 2) if (i % 2 !== 0) oddNumbers.push(i);
if문이 필요한가요?

2024-03-16 09:54 UTC, lgyn10 commented on day23/세균증식.ts
> +  }
어떻게든 Lodash 함수들을 써보고자 했더니, 과도하게 남용하게 되었군요..!ㅠ

2024-03-16 09:54 UTC, lgyn10 commented on day23/짝수는싫어요.ts
> +  for (let i = 1; i <= n; i += 2) oddNumbers.push(i);
수정했습니다!

2024-03-16 09:55 UTC, lgyn10 commented on day23/짝수는싫어요.ts
> +  for (let i = 1; i <= n; i += 2) if (i % 2 !== 0) oddNumbers.push(i);
필요없네요...ㅠ

2024-03-16 09:55 UTC, lgyn10 commented on day23/세균증식.ts
> +    cnts = multiply(cnts, 2);
넵!

2024-03-17 04:17 UTC, f-lab-jake approved these changes

2024-03-17 04:17 UTC, f-lab-jake commented on day23/짝수는싫어요.ts
> +  for (let i = 1; i <= n; i += 2) oddNumbers.push(i);
사실 `range` 한방으로 할수있기도 합니다

2024-03-17 06:51 UTC, lgyn10 commented on day23/짝수는싫어요.ts
> +  for (let i = 1; i <= n; i += 2) oddNumbers.push(i);
오..! 코드 추가해서 머시하겠습니다!

2024-03-17 06:51 UTC, merged