Day24
f-lab-edu/alg-everyday pull request #34
Opened 2024-03-16 09:49 UTC by lgyn10

2024-03-17 04:21 UTC, f-lab-jake requested changes

2024-03-17 04:21 UTC, f-lab-jake commented on day24/더맵게.ts
> +    scoville.splice(0, 2);
```ts
const mixedFood = scovilleOfMixedFood(...scoville.splice(0, 2))
```
요렇게 할수있겠죠?

2024-03-17 04:21 UTC, f-lab-jake commented on day24/더맵게.ts
> +  getMinValue(): number {
얘를 그냥 `pop`으로 이름지어줘도 됩니다. 힙이 겉에서볼땐 스택의 인터페이스를 합니다. 마찬가지로 `insert` 대신에 `push`하면 더 자연스럽겠죠.

2024-03-17 04:21 UTC, f-lab-jake commented on day24/옷가게할인.ts
> +  else return price;
중복을 줄여보세요

2024-03-17 07:41 UTC, lgyn10 commented on day24/옷가게할인.ts
> +};
if문이 중복되는 코드를 수정해보았습니다..! 

좀 더 간단하게 표현하는 방법이 있을까요...?

2024-03-17 07:41 UTC, lgyn10 commented on day24/더맵게.ts
> +    const mixedFood = scovilleOfMixedFood(...(scoville.splice(0, 2) as [number, number]));
피드백을 적용하여 수정해보았습니다!

2024-03-17 07:41 UTC, lgyn10 commented on day24/더맵게.ts
> +class MinHeap {
힙 구조에 대해 학습한 내용을 복기해보니, 트리 구조는 사람이 이해하기 쉽게 시각화한 것이고 실제로는 배열 구조를 활용하는 것을 다시 인지했습니다!

2024-03-18 02:14 UTC, f-lab-jake approved these changes

2024-03-18 02:16 UTC, f-lab-jake requested changes

2024-03-18 02:16 UTC, f-lab-jake commented on day24/옷가게할인.ts
> +  return price * discountPers[idx];
`find`쓰면 되겠죠?

2024-03-18 02:16 UTC, f-lab-jake commented on day24/옷가게할인.ts
> +  const discountPers = [0.95, 0.9, 0.8];
이건 두 배열의 길이가 실수로 달라지면 찾기어려운 버그를 발생시키게 됩니다. 튜플 형식으로 하는게 맞습니다.

2024-03-18 07:52 UTC, lgyn10 commented on day24/옷가게할인.ts
> +  return price * discountPers[idx];
@f-lab-jake 
`findLast`를 통해 최종 할인율을 리턴하도록 수정했습니다!

2024-03-18 07:53 UTC, lgyn10 commented on day24/옷가게할인.ts
> +  const discountPers = [0.95, 0.9, 0.8];
@f-lab-jake 
튜플구조를 의식적으로라도 사용하려고 노력해야겠습니다..!

2024-03-18 08:09 UTC, merged