Day26
f-lab-edu/alg-everyday pull request #37
Opened 2024-03-18 08:52 UTC by lgyn10

2024-03-18 14:01 UTC, f-lab-jake requested changes

2024-03-18 14:01 UTC, f-lab-jake commented on day26/최댓값만들기2.ts
> +  const cmp2 = numbers[numsLen - 2] * numbers[numsLen - 1];
`at`을 써보세요

2024-03-26 04:10 UTC, lgyn10 commented on day26/문자열정렬하기1.ts
> +};
> 숫자로 변환하는 과정을 거치지않고(parseInt)등을 안쓰고 풀어볼까요?

숫자로 변환하지 않고, 정규식을 이용하여 숫자들을 먼저 걸러냈습니다!
마지막에 답을 도출할 때는 `number[]` 타입이여서 `parseInt`를 부득이하게 사용해야하는 것 같습니다...!

2024-03-26 04:10 UTC, lgyn10 commented on day26/최댓값만들기2.ts
> +  const cmp2 = numbers.at(-1)! * numbers.at(-2)!;
> at을 써보세요

`at()` 사용을 통해 배열 마지막 요소들을 접근하는 표현에 있어서 좀 더 명시적이여서 사용을 의도하신 걸까요..?!

2024-03-26 04:10 UTC, lgyn10 commented on day26/약수구하기.ts
> +};
`Math.sqrt(n)`까지만 순회하도록 수정하였습니다!

2024-03-26 04:58 UTC, f-lab-jake approved these changes

2024-03-26 04:58 UTC, f-lab-jake commented on day26/문자열정렬하기1.ts
> +};
마지막에 `parseInt`하는 것은 자연스럽습니다. 숫자끼리 대소비교를 해야하니까요.
그런데 이렇게하면 결국 1. 숫자가 맞는지 확인, 2. 숫자로 파싱을 따로따로하는 문제가 있긴합니다.
`parseInt`가 `NaN` 리턴하는 동작이 맘에 들지 않아서 이렇게 바꾸라고 한건데, 원래 파싱와 validation은 한번에 하는게 낫습니다.

2024-03-26 04:58 UTC, f-lab-jake commented on day26/약수구하기.ts
> +      ans2.unshift(n / i);
`unshift`가 성능이 안좋긴 합니다만, 의미론상 맞는 코드입니다.

2024-03-26 04:58 UTC, f-lab-jake commented on day26/최댓값만들기2.ts
> +  const cmp2 = numbers.at(-1)! * numbers.at(-2)!;
넵

2024-03-26 12:09 UTC, lgyn10 commented on day26/문자열정렬하기1.ts
> +};
@f-lab-jake 
그러면, 빈배열을 선언하고 `forEach` 함수로 validation과 파싱을 한번에 하는 로직이 좋겠군요..!

2024-03-26 12:12 UTC, lgyn10 commented on day26/약수구하기.ts
> +      ans2.unshift(n / i);
@f-lab-jake 
```
  const ans1 = [];
  const ans2 = [];
  const nSqrt = Math.sqrt(n);

  for (let i = 1; i < nSqrt; i++) {
    if (n % i === 0) {
      ans1.push(i);
      // ans2.unshift(n / i);
      ans2.push(n / i);
    }
  }
  if (Number.isInteger(nSqrt)) ans1.push(nSqrt);

  return [...ans1, ...ans2.reverse()];
  ```
  이렇게 `push`로만 코드를 짜고, `reverse()` 함수를 사용하는게 성능면에서 좋을까요..?

2024-03-27 11:51 UTC, lgyn10 commented on day26/문자열정렬하기1.ts
> +};
> 그러면, 빈배열을 선언하고 `forEach` 함수로 validation과 파싱을 한번에 하는 로직이 좋겠군요..!

위의 댓글은 무시한다.!

2024-03-27 11:52 UTC, merged