day3 1231일자 문제풀이
f-lab-edu/alg-everyday pull request #4
Opened 2023-12-31 09:48 UTC by lgyn10

2023-12-31 13:16 UTC, f-lab-jake requested changes

2023-12-31 13:16 UTC, f-lab-jake commented on 문자열다루기기본.js
> +  return false;
더 줄여 봅시다

2023-12-31 13:16 UTC, f-lab-jake commented on 행렬의덧셈.js
> +  });
`zip`을 써봅시다.

2023-12-31 13:16 UTC, f-lab-jake commented on 행렬의덧셈.js
> +  });
그리고 arrow fucntion쓸때 return의 사용을 피하는게 간결합니다.

2024-01-01 09:19 UTC, lgyn10 commented on 문자열다루기기본.js
> +  return false;
줄였습니다!

2024-01-01 09:22 UTC, lgyn10 commented on 행렬의덧셈.js
> +  });
zip함수를 이용하고, 필요없는 return 문도 생략했습니다!

2024-01-01 11:54 UTC, f-lab-jake requested changes

2024-01-01 11:54 UTC, f-lab-jake commented on 행렬의덧셈.js
> +  return zippedArr.map(([v1, v2]) => v1.map((v, i) => v + v2[i]));
인덱스 사용을 피해보세요. `zip`을 활용하면됩니다.

2024-01-01 11:54 UTC, f-lab-jake commented on 문자열다루기기본.js
>    return false;
if문 쓰지말아봅시다.

2024-01-01 13:43 UTC, lgyn10 commented on day3/행렬의덧셈.js
> +}
행렬의 길이가 가변적인 상황에서 인덱스를 쓰지 않는 법을 잘 모르겠습니다.

2024-01-01 13:43 UTC, lgyn10 commented on day3/문자열다루기기본.js
> +}
if문을 제거해보았습니다. 하지만 중첩 삼항 연산자를 이용하게 되는데 어떤 이유로 if문을 제거하는 것을 추천하셨는지 궁금합니다. 
코드의 양이 줄어들면 어느 정도는 가독성이 좋아진다고 알고 있지만, 이번 문제에서는 개인적인 시선으로 코드 이해가 더 어려워지는 것 아닌가 싶습니다. 

다른 표현 법이 있는데 제가 알지 못한 것인지, 이러한 코드가 현장에서 많이 쓰여 눈에 익히는 것이 좋은 것인지..
멘토님의 의견이 궁금합니다!

2024-01-02 04:53 UTC, f-lab-jake commented on day3/행렬의덧셈.js
> +}
`v1`과 `v2`는 길이가 같습니다

2024-01-02 04:54 UTC, f-lab-jake commented on day3/문자열다루기기본.js
> +}
삼항연산자에 `false` `true`를 쓰는걸 피해보세요

2024-01-02 15:25 UTC, lgyn10 commented on day3/문자열다루기기본.js
> +}
오! 왜 이게 어제는 보이지 않았는지 모르겠네요..

2024-01-02 15:25 UTC, lgyn10 commented on day3/행렬의덧셈.js
> +}
`zipWith`이라는 함수도 새로 배워 써서 풀었습니다!

2024-01-02 23:58 UTC, f-lab-jake commented on day3/행렬의덧셈.js
> +}
`zipWith`스스로 찾아낸거 아주 좋습니다. 그런데 한번 더 적용할 수 있습니다

2024-01-02 23:59 UTC, f-lab-jake commented on day3/문자열다루기기본.js
> +}
잘했습니다. 그런데 좀더 줄일수 있습니다.
코드를 줄이라는게 그냥 이리저리 스타일을 바꿔보란게 아니고, 코드가 진짜로 담아야할 의미를 찾아내서 적용하란 겁니다.
저 코드의 의미를 생각하고 그걸 그대로 반영하는 코드를 짭시다.

2024-01-05 01:58 UTC, f-lab-jake approved these changes

2024-01-05 23:08 UTC, closed without merging