241108 금요일
f-lab-edu/alg-everyday pull request #40
Opened 2024-11-08 04:58 UTC by lgyn10

프로그래머스 lv.0
- 연속된 수의 합
- 안전 지대

2024-11-08 15:36 UTC, f-lab-jake requested changes

2024-11-08 15:36 UTC, f-lab-jake commented on 1.programmers/lv.0/안전지대.ts
> +  const bombLoc: number[][] = [];
타입을 개선하세요. 튜플 타입을 쓰세요.

2024-11-08 15:36 UTC, f-lab-jake commented on 1.programmers/lv.0/안전지대.ts
> +  const addStringToSet = (n: number, m: number): void => {
무슨 의미인가요? 변수명을 개선하세요.

2024-11-08 15:36 UTC, f-lab-jake commented on 1.programmers/lv.0/안전지대.ts
> +  const addStringToSet = (n: number, m: number): void => {
기존의 이름이 왜 안좋은지도 설명해보세요.

2024-11-11 06:31 UTC, lgyn10 commented on 1.programmers/lv.0/안전지대.ts
> +  const bombLoc: number[][] = [];
[8c83bc2](https://github.com/f-lab-edu/alg-everyday/pull/40/commits/8c83bc27a9098e750a96d8f1f8694651b9853a56)에서 반영했습니다!

2024-11-11 06:37 UTC, lgyn10 commented on 1.programmers/lv.0/안전지대.ts
> +  const addStringToSet = (n: number, m: number): void => {
[d12e1cb](https://github.com/f-lab-edu/alg-everyday/pull/40/commits/d12e1cbb8d489387844427b1bf17d206a6674c6f)에서 개선하였습니다!

기존 `fatalZone`에서 `dangerZone`으로 변경헀습니다. 이는 더 직관적이고 명확한 의미를 전달한다고 생각했습니다. 

하지만, 이보다도 `addStringToSet`이라는 함수명이 굉장히 바람직하지 않음을 깨닳았습니다. 
함수명은 그 함수의 목적을 나타내야하는데, `addStringToSet`은 함수의 목적을 나타내지 못하고 있습니다. 

찾아보니, 함수명은 `무엇을 하는가`를 나타내야지, `어떻게 하는가`에 초점이 맞춰지면 안된다고 합니다.

`addStringToSet`이라는 함수명은 `어떻게 하는가`에 초점이 맞춰진 이름이기 때문에 잘못된 이름입니다!

2024-11-11 07:10 UTC, f-lab-jake approved these changes

2024-11-11 07:26 UTC, merged