241114 tue
f-lab-edu/alg-everyday pull request #42
Opened 2024-11-14 02:49 UTC by lgyn10

2024-11-14 12:44 UTC, f-lab-jake requested changes

2024-11-15 03:18 UTC, lgyn10 commented on 1.programmers/lv.0/옹알이(1).ts
> +    tempWord = tempWord.replaceAll(' ', '');
@f-lab-jake 
처음에는
```js
    for (const pronounceable of pronounceableSet) {
      tempWord = tempWord.replace(pronounceable, '');
    }
   ```
로 작성했는데, `wyeoo`인 경우에 반례가 생겼습니다. 이 부분을 해결하기 위해 
`tempWord = tempWord.replace(pronounceable, '');` -> `tempWord = tempWord.replace(pronounceable, ' ');`로 변경 후 
`tempWord = tempWord.replaceAll(' ', '');`로 반례를 해결할 수 있었습니다. 

그런데 이보다 더 효율적인 방법이 떠오르지 않는데요...

힌트가 필요합니다..!!

2024-11-15 03:22 UTC, lgyn10 commented on 1.programmers/lv.0/평행.ts
> +  }
[19e35e3](https://github.com/f-lab-edu/alg-everyday/pull/42/commits/19e35e389aa6f94e8b9b862ac5f89429e354839f)에서 수정했습니다!

2024-11-16 04:14 UTC, f-lab-jake commented on 1.programmers/lv.0/평행.ts
> +  }
대칭이 더 있습니다

2024-11-16 04:15 UTC, f-lab-jake requested changes

2024-11-16 04:15 UTC, f-lab-jake commented on 1.programmers/lv.0/옹알이(1).ts
> +    tempWord = tempWord.replaceAll(' ', '');
`replace`를 쓰지말고 앞에서부터 읽어보세요

2024-11-18 00:27 UTC, lgyn10 commented on 1.programmers/lv.0/평행.ts
> +  }
<img width="411" alt="스크린샷 2024-11-18 오전 9 26 04" src="https://github.com/user-attachments/assets/ccdac4bd-b775-41a2-beab-cea61aebad75">
i와 j의 대칭은 더 이상 확인되지 않는데, 다른 부분에서 대칭이 있는걸까요?

2024-11-18 00:50 UTC, lgyn10 commented on 1.programmers/lv.0/옹알이(1).ts
> +    tempWord = tempWord.replaceAll(' ', '');
어떤 말씀이신지 이해가 되지 않습니다..

2024-11-18 14:01 UTC, f-lab-jake requested changes

2024-11-18 14:01 UTC, f-lab-jake commented on 1.programmers/lv.0/평행.ts
> +  }
대칭이 더 있습니다.

2024-11-27 00:05 UTC, merged