Day5
f-lab-edu/alg-everyday pull request #8
Opened 2024-01-04 13:28 UTC by lgyn10

2024-01-04 13:31 UTC, lgyn10 commented on day5/시저암호.js
> +}
고민을 많이 했는데, 이것보다 더 줄일 수 있는건가요.........ㅠㅠㅠㅠㅠㅠㅠ

2024-01-05 01:57 UTC, f-lab-jake requested changes

2024-01-05 01:57 UTC, f-lab-jake commented on day5/삼총사.js
> +  num.map((v1) => num.map((v2) => num.map((v3) => v1 + v2 + v3 === 0 && arr.push([v1, v2, v3].sort((a, b) => a - b)))));
`map`에서 외부변수를 변경하는 일을 피합시다. 이유에 대해선 다음 멘토링때 얘기해봅시다.
return값을 사용하지 않는 `ma`p은 의심스러워 보입니다.

2024-01-05 01:57 UTC, f-lab-jake commented on day5/시저암호.js
> +      return 32;
90, 26 과 같은 숫자를 magic number라고 합니다.
무슨 근거로 제기된 값인지 이해하기 어렵습니다. 
magic number를 제거하고, 또 중복도 제거합시다.

2024-01-05 01:57 UTC, f-lab-jake commented on day5/시저암호.js
> +}
일단 의미를 기준으로 줄여야합니다.
그런데 의미에 대해서 생각하는게 어려우면 코드의 생김새를 보고 힌트를 얻을수 있습니다. 가령 지금 `ascNumSum > x ? ascNumSum - y : ascNumSum` 요런 꼴이 2번 나오죠? 저 동작의 의미가 뭘까요?

2024-01-05 01:57 UTC, f-lab-jake commented on day5/최소직사각형.js
> +  return _.max(arr.map(_.min)) * _.max(arr.map(_.max));
중간값에 이름을 주어 변수로 만듭시다. `arr.map(_.min)` 요런게 뭘 의미하는지 이해하기가 어렵습니다.

2024-01-05 23:08 UTC, closed without merging